// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 04 Jul 2017 10:30:17 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include <GLES3/gl31.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

