// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 11 Jan 2017 21:27:08 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include <GLES3/gl31.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

