// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 26 Feb 2017 06:20:47 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package gles31 provides Go bindings for the OpenGL ES v3.1 API.
*/
package gles31
