// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 26 Feb 2017 06:20:46 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include <GLES3/gl3.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

