// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Jan 2017 23:24:01 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package gles3

/*
#cgo LDFLAGS: -lGLESv3
#include <GLES3/gl3.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// EsVersion20 as defined in GLES3/gl3.h:54
	EsVersion20 = 1
	// DepthBufferBit as defined in GLES3/gl3.h:76
	DepthBufferBit = 0x00000100
	// StencilBufferBit as defined in GLES3/gl3.h:77
	StencilBufferBit = 0x00000400
	// ColorBufferBit as defined in GLES3/gl3.h:78
	ColorBufferBit = 0x00004000
	// False as defined in GLES3/gl3.h:79
	False = 0
	// True as defined in GLES3/gl3.h:80
	True = 1
	// Points as defined in GLES3/gl3.h:81
	Points = 0x0000
	// Lines as defined in GLES3/gl3.h:82
	Lines = 0x0001
	// LineLoop as defined in GLES3/gl3.h:83
	LineLoop = 0x0002
	// LineStrip as defined in GLES3/gl3.h:84
	LineStrip = 0x0003
	// Triangles as defined in GLES3/gl3.h:85
	Triangles = 0x0004
	// TriangleStrip as defined in GLES3/gl3.h:86
	TriangleStrip = 0x0005
	// TriangleFan as defined in GLES3/gl3.h:87
	TriangleFan = 0x0006
	// Zero as defined in GLES3/gl3.h:88
	Zero = 0
	// One as defined in GLES3/gl3.h:89
	One = 1
	// SrcColor as defined in GLES3/gl3.h:90
	SrcColor = 0x0300
	// OneMinusSrcColor as defined in GLES3/gl3.h:91
	OneMinusSrcColor = 0x0301
	// SrcAlpha as defined in GLES3/gl3.h:92
	SrcAlpha = 0x0302
	// OneMinusSrcAlpha as defined in GLES3/gl3.h:93
	OneMinusSrcAlpha = 0x0303
	// DstAlpha as defined in GLES3/gl3.h:94
	DstAlpha = 0x0304
	// OneMinusDstAlpha as defined in GLES3/gl3.h:95
	OneMinusDstAlpha = 0x0305
	// DstColor as defined in GLES3/gl3.h:96
	DstColor = 0x0306
	// OneMinusDstColor as defined in GLES3/gl3.h:97
	OneMinusDstColor = 0x0307
	// SrcAlphaSaturate as defined in GLES3/gl3.h:98
	SrcAlphaSaturate = 0x0308
	// FuncAdd as defined in GLES3/gl3.h:99
	FuncAdd = 0x8006
	// BlendEquation as defined in GLES3/gl3.h:100
	BlendEquation = 0x8009
	// BlendEquationRgb as defined in GLES3/gl3.h:101
	BlendEquationRgb = 0x8009
	// BlendEquationAlpha as defined in GLES3/gl3.h:102
	BlendEquationAlpha = 0x883D
	// FuncSubtract as defined in GLES3/gl3.h:103
	FuncSubtract = 0x800A
	// FuncReverseSubtract as defined in GLES3/gl3.h:104
	FuncReverseSubtract = 0x800B
	// BlendDstRgb as defined in GLES3/gl3.h:105
	BlendDstRgb = 0x80C8
	// BlendSrcRgb as defined in GLES3/gl3.h:106
	BlendSrcRgb = 0x80C9
	// BlendDstAlpha as defined in GLES3/gl3.h:107
	BlendDstAlpha = 0x80CA
	// BlendSrcAlpha as defined in GLES3/gl3.h:108
	BlendSrcAlpha = 0x80CB
	// ConstantColor as defined in GLES3/gl3.h:109
	ConstantColor = 0x8001
	// OneMinusConstantColor as defined in GLES3/gl3.h:110
	OneMinusConstantColor = 0x8002
	// ConstantAlpha as defined in GLES3/gl3.h:111
	ConstantAlpha = 0x8003
	// OneMinusConstantAlpha as defined in GLES3/gl3.h:112
	OneMinusConstantAlpha = 0x8004
	// BlendColor as defined in GLES3/gl3.h:113
	BlendColor = 0x8005
	// ArrayBuffer as defined in GLES3/gl3.h:114
	ArrayBuffer = 0x8892
	// ElementArrayBuffer as defined in GLES3/gl3.h:115
	ElementArrayBuffer = 0x8893
	// ArrayBufferBinding as defined in GLES3/gl3.h:116
	ArrayBufferBinding = 0x8894
	// ElementArrayBufferBinding as defined in GLES3/gl3.h:117
	ElementArrayBufferBinding = 0x8895
	// StreamDraw as defined in GLES3/gl3.h:118
	StreamDraw = 0x88E0
	// StaticDraw as defined in GLES3/gl3.h:119
	StaticDraw = 0x88E4
	// DynamicDraw as defined in GLES3/gl3.h:120
	DynamicDraw = 0x88E8
	// BufferSize as defined in GLES3/gl3.h:121
	BufferSize = 0x8764
	// BufferUsage as defined in GLES3/gl3.h:122
	BufferUsage = 0x8765
	// CurrentVertexAttrib as defined in GLES3/gl3.h:123
	CurrentVertexAttrib = 0x8626
	// Front as defined in GLES3/gl3.h:124
	Front = 0x0404
	// Back as defined in GLES3/gl3.h:125
	Back = 0x0405
	// FrontAndBack as defined in GLES3/gl3.h:126
	FrontAndBack = 0x0408
	// Texture2d as defined in GLES3/gl3.h:127
	Texture2d = 0x0DE1
	// CullFace as defined in GLES3/gl3.h:128
	CullFace = 0x0B44
	// Blend as defined in GLES3/gl3.h:129
	Blend = 0x0BE2
	// Dither as defined in GLES3/gl3.h:130
	Dither = 0x0BD0
	// StencilTest as defined in GLES3/gl3.h:131
	StencilTest = 0x0B90
	// DepthTest as defined in GLES3/gl3.h:132
	DepthTest = 0x0B71
	// ScissorTest as defined in GLES3/gl3.h:133
	ScissorTest = 0x0C11
	// PolygonOffsetFill as defined in GLES3/gl3.h:134
	PolygonOffsetFill = 0x8037
	// SampleAlphaToCoverage as defined in GLES3/gl3.h:135
	SampleAlphaToCoverage = 0x809E
	// SampleCoverage as defined in GLES3/gl3.h:136
	SampleCoverage = 0x80A0
	// NoError as defined in GLES3/gl3.h:137
	NoError = 0
	// InvalidEnum as defined in GLES3/gl3.h:138
	InvalidEnum = 0x0500
	// InvalidValue as defined in GLES3/gl3.h:139
	InvalidValue = 0x0501
	// InvalidOperation as defined in GLES3/gl3.h:140
	InvalidOperation = 0x0502
	// OutOfMemory as defined in GLES3/gl3.h:141
	OutOfMemory = 0x0505
	// Cw as defined in GLES3/gl3.h:142
	Cw = 0x0900
	// Ccw as defined in GLES3/gl3.h:143
	Ccw = 0x0901
	// LineWidth as defined in GLES3/gl3.h:144
	LineWidth = 0x0B21
	// AliasedPointSizeRange as defined in GLES3/gl3.h:145
	AliasedPointSizeRange = 0x846D
	// AliasedLineWidthRange as defined in GLES3/gl3.h:146
	AliasedLineWidthRange = 0x846E
	// CullFaceMode as defined in GLES3/gl3.h:147
	CullFaceMode = 0x0B45
	// FrontFace as defined in GLES3/gl3.h:148
	FrontFace = 0x0B46
	// DepthRange as defined in GLES3/gl3.h:149
	DepthRange = 0x0B70
	// DepthWritemask as defined in GLES3/gl3.h:150
	DepthWritemask = 0x0B72
	// DepthClearValue as defined in GLES3/gl3.h:151
	DepthClearValue = 0x0B73
	// DepthFunc as defined in GLES3/gl3.h:152
	DepthFunc = 0x0B74
	// StencilClearValue as defined in GLES3/gl3.h:153
	StencilClearValue = 0x0B91
	// StencilFunc as defined in GLES3/gl3.h:154
	StencilFunc = 0x0B92
	// StencilFail as defined in GLES3/gl3.h:155
	StencilFail = 0x0B94
	// StencilPassDepthFail as defined in GLES3/gl3.h:156
	StencilPassDepthFail = 0x0B95
	// StencilPassDepthPass as defined in GLES3/gl3.h:157
	StencilPassDepthPass = 0x0B96
	// StencilRef as defined in GLES3/gl3.h:158
	StencilRef = 0x0B97
	// StencilValueMask as defined in GLES3/gl3.h:159
	StencilValueMask = 0x0B93
	// StencilWritemask as defined in GLES3/gl3.h:160
	StencilWritemask = 0x0B98
	// StencilBackFunc as defined in GLES3/gl3.h:161
	StencilBackFunc = 0x8800
	// StencilBackFail as defined in GLES3/gl3.h:162
	StencilBackFail = 0x8801
	// StencilBackPassDepthFail as defined in GLES3/gl3.h:163
	StencilBackPassDepthFail = 0x8802
	// StencilBackPassDepthPass as defined in GLES3/gl3.h:164
	StencilBackPassDepthPass = 0x8803
	// StencilBackRef as defined in GLES3/gl3.h:165
	StencilBackRef = 0x8CA3
	// StencilBackValueMask as defined in GLES3/gl3.h:166
	StencilBackValueMask = 0x8CA4
	// StencilBackWritemask as defined in GLES3/gl3.h:167
	StencilBackWritemask = 0x8CA5
	// Viewport as defined in GLES3/gl3.h:168
	Viewport = 0x0BA2
	// ScissorBox as defined in GLES3/gl3.h:169
	ScissorBox = 0x0C10
	// ColorClearValue as defined in GLES3/gl3.h:170
	ColorClearValue = 0x0C22
	// ColorWritemask as defined in GLES3/gl3.h:171
	ColorWritemask = 0x0C23
	// UnpackAlignment as defined in GLES3/gl3.h:172
	UnpackAlignment = 0x0CF5
	// PackAlignment as defined in GLES3/gl3.h:173
	PackAlignment = 0x0D05
	// MaxTextureSize as defined in GLES3/gl3.h:174
	MaxTextureSize = 0x0D33
	// MaxViewportDims as defined in GLES3/gl3.h:175
	MaxViewportDims = 0x0D3A
	// SubpixelBits as defined in GLES3/gl3.h:176
	SubpixelBits = 0x0D50
	// RedBits as defined in GLES3/gl3.h:177
	RedBits = 0x0D52
	// GreenBits as defined in GLES3/gl3.h:178
	GreenBits = 0x0D53
	// BlueBits as defined in GLES3/gl3.h:179
	BlueBits = 0x0D54
	// AlphaBits as defined in GLES3/gl3.h:180
	AlphaBits = 0x0D55
	// DepthBits as defined in GLES3/gl3.h:181
	DepthBits = 0x0D56
	// StencilBits as defined in GLES3/gl3.h:182
	StencilBits = 0x0D57
	// PolygonOffsetUnits as defined in GLES3/gl3.h:183
	PolygonOffsetUnits = 0x2A00
	// PolygonOffsetFactor as defined in GLES3/gl3.h:184
	PolygonOffsetFactor = 0x8038
	// TextureBinding2d as defined in GLES3/gl3.h:185
	TextureBinding2d = 0x8069
	// SampleBuffers as defined in GLES3/gl3.h:186
	SampleBuffers = 0x80A8
	// Samples as defined in GLES3/gl3.h:187
	Samples = 0x80A9
	// SampleCoverageValue as defined in GLES3/gl3.h:188
	SampleCoverageValue = 0x80AA
	// SampleCoverageInvert as defined in GLES3/gl3.h:189
	SampleCoverageInvert = 0x80AB
	// NumCompressedTextureFormats as defined in GLES3/gl3.h:190
	NumCompressedTextureFormats = 0x86A2
	// CompressedTextureFormats as defined in GLES3/gl3.h:191
	CompressedTextureFormats = 0x86A3
	// DontCare as defined in GLES3/gl3.h:192
	DontCare = 0x1100
	// Fastest as defined in GLES3/gl3.h:193
	Fastest = 0x1101
	// Nicest as defined in GLES3/gl3.h:194
	Nicest = 0x1102
	// GenerateMipmapHintType as defined in GLES3/gl3.h:195
	GenerateMipmapHintType = 0x8192
	// ByteType as defined in GLES3/gl3.h:196
	ByteType = 0x1400
	// UnsignedByteType as defined in GLES3/gl3.h:197
	UnsignedByteType = 0x1401
	// ShortType as defined in GLES3/gl3.h:198
	ShortType = 0x1402
	// UnsignedShortType as defined in GLES3/gl3.h:199
	UnsignedShortType = 0x1403
	// IntType as defined in GLES3/gl3.h:200
	IntType = 0x1404
	// UnsignedIntType as defined in GLES3/gl3.h:201
	UnsignedIntType = 0x1405
	// FloatType as defined in GLES3/gl3.h:202
	FloatType = 0x1406
	// FixedType as defined in GLES3/gl3.h:203
	FixedType = 0x140C
	// DepthComponent as defined in GLES3/gl3.h:204
	DepthComponent = 0x1902
	// Alpha as defined in GLES3/gl3.h:205
	Alpha = 0x1906
	// Rgb as defined in GLES3/gl3.h:206
	Rgb = 0x1907
	// Rgba as defined in GLES3/gl3.h:207
	Rgba = 0x1908
	// Luminance as defined in GLES3/gl3.h:208
	Luminance = 0x1909
	// LuminanceAlpha as defined in GLES3/gl3.h:209
	LuminanceAlpha = 0x190A
	// UnsignedShort4444 as defined in GLES3/gl3.h:210
	UnsignedShort4444 = 0x8033
	// UnsignedShort5551 as defined in GLES3/gl3.h:211
	UnsignedShort5551 = 0x8034
	// UnsignedShort565 as defined in GLES3/gl3.h:212
	UnsignedShort565 = 0x8363
	// FragmentShader as defined in GLES3/gl3.h:213
	FragmentShader = 0x8B30
	// VertexShader as defined in GLES3/gl3.h:214
	VertexShader = 0x8B31
	// MaxVertexAttribs as defined in GLES3/gl3.h:215
	MaxVertexAttribs = 0x8869
	// MaxVertexUniformVectors as defined in GLES3/gl3.h:216
	MaxVertexUniformVectors = 0x8DFB
	// MaxVaryingVectors as defined in GLES3/gl3.h:217
	MaxVaryingVectors = 0x8DFC
	// MaxCombinedTextureImageUnits as defined in GLES3/gl3.h:218
	MaxCombinedTextureImageUnits = 0x8B4D
	// MaxVertexTextureImageUnits as defined in GLES3/gl3.h:219
	MaxVertexTextureImageUnits = 0x8B4C
	// MaxTextureImageUnits as defined in GLES3/gl3.h:220
	MaxTextureImageUnits = 0x8872
	// MaxFragmentUniformVectors as defined in GLES3/gl3.h:221
	MaxFragmentUniformVectors = 0x8DFD
	// ShaderType as defined in GLES3/gl3.h:222
	ShaderType = 0x8B4F
	// DeleteStatus as defined in GLES3/gl3.h:223
	DeleteStatus = 0x8B80
	// LinkStatus as defined in GLES3/gl3.h:224
	LinkStatus = 0x8B82
	// ValidateStatus as defined in GLES3/gl3.h:225
	ValidateStatus = 0x8B83
	// AttachedShaders as defined in GLES3/gl3.h:226
	AttachedShaders = 0x8B85
	// ActiveUniforms as defined in GLES3/gl3.h:227
	ActiveUniforms = 0x8B86
	// ActiveUniformMaxLength as defined in GLES3/gl3.h:228
	ActiveUniformMaxLength = 0x8B87
	// ActiveAttributes as defined in GLES3/gl3.h:229
	ActiveAttributes = 0x8B89
	// ActiveAttributeMaxLength as defined in GLES3/gl3.h:230
	ActiveAttributeMaxLength = 0x8B8A
	// ShadingLanguageVersion as defined in GLES3/gl3.h:231
	ShadingLanguageVersion = 0x8B8C
	// CurrentProgram as defined in GLES3/gl3.h:232
	CurrentProgram = 0x8B8D
	// Never as defined in GLES3/gl3.h:233
	Never = 0x0200
	// Less as defined in GLES3/gl3.h:234
	Less = 0x0201
	// Equal as defined in GLES3/gl3.h:235
	Equal = 0x0202
	// Lequal as defined in GLES3/gl3.h:236
	Lequal = 0x0203
	// Greater as defined in GLES3/gl3.h:237
	Greater = 0x0204
	// Notequal as defined in GLES3/gl3.h:238
	Notequal = 0x0205
	// Gequal as defined in GLES3/gl3.h:239
	Gequal = 0x0206
	// Always as defined in GLES3/gl3.h:240
	Always = 0x0207
	// Keep as defined in GLES3/gl3.h:241
	Keep = 0x1E00
	// Replace as defined in GLES3/gl3.h:242
	Replace = 0x1E01
	// Incr as defined in GLES3/gl3.h:243
	Incr = 0x1E02
	// Decr as defined in GLES3/gl3.h:244
	Decr = 0x1E03
	// Invert as defined in GLES3/gl3.h:245
	Invert = 0x150A
	// IncrWrap as defined in GLES3/gl3.h:246
	IncrWrap = 0x8507
	// DecrWrap as defined in GLES3/gl3.h:247
	DecrWrap = 0x8508
	// Vendor as defined in GLES3/gl3.h:248
	Vendor = 0x1F00
	// Renderer as defined in GLES3/gl3.h:249
	Renderer = 0x1F01
	// Version as defined in GLES3/gl3.h:250
	Version = 0x1F02
	// Extensions as defined in GLES3/gl3.h:251
	Extensions = 0x1F03
	// Nearest as defined in GLES3/gl3.h:252
	Nearest = 0x2600
	// Linear as defined in GLES3/gl3.h:253
	Linear = 0x2601
	// NearestMipmapNearest as defined in GLES3/gl3.h:254
	NearestMipmapNearest = 0x2700
	// LinearMipmapNearest as defined in GLES3/gl3.h:255
	LinearMipmapNearest = 0x2701
	// NearestMipmapLinear as defined in GLES3/gl3.h:256
	NearestMipmapLinear = 0x2702
	// LinearMipmapLinear as defined in GLES3/gl3.h:257
	LinearMipmapLinear = 0x2703
	// TextureMagFilter as defined in GLES3/gl3.h:258
	TextureMagFilter = 0x2800
	// TextureMinFilter as defined in GLES3/gl3.h:259
	TextureMinFilter = 0x2801
	// TextureWrapS as defined in GLES3/gl3.h:260
	TextureWrapS = 0x2802
	// TextureWrapT as defined in GLES3/gl3.h:261
	TextureWrapT = 0x2803
	// Texture as defined in GLES3/gl3.h:262
	Texture = 0x1702
	// TextureCubeMap as defined in GLES3/gl3.h:263
	TextureCubeMap = 0x8513
	// TextureBindingCubeMap as defined in GLES3/gl3.h:264
	TextureBindingCubeMap = 0x8514
	// TextureCubeMapPositiveX as defined in GLES3/gl3.h:265
	TextureCubeMapPositiveX = 0x8515
	// TextureCubeMapNegativeX as defined in GLES3/gl3.h:266
	TextureCubeMapNegativeX = 0x8516
	// TextureCubeMapPositiveY as defined in GLES3/gl3.h:267
	TextureCubeMapPositiveY = 0x8517
	// TextureCubeMapNegativeY as defined in GLES3/gl3.h:268
	TextureCubeMapNegativeY = 0x8518
	// TextureCubeMapPositiveZ as defined in GLES3/gl3.h:269
	TextureCubeMapPositiveZ = 0x8519
	// TextureCubeMapNegativeZ as defined in GLES3/gl3.h:270
	TextureCubeMapNegativeZ = 0x851A
	// MaxCubeMapTextureSize as defined in GLES3/gl3.h:271
	MaxCubeMapTextureSize = 0x851C
	// Texture0 as defined in GLES3/gl3.h:272
	Texture0 = 0x84C0
	// Texture1 as defined in GLES3/gl3.h:273
	Texture1 = 0x84C1
	// Texture2 as defined in GLES3/gl3.h:274
	Texture2 = 0x84C2
	// Texture3 as defined in GLES3/gl3.h:275
	Texture3 = 0x84C3
	// Texture4 as defined in GLES3/gl3.h:276
	Texture4 = 0x84C4
	// Texture5 as defined in GLES3/gl3.h:277
	Texture5 = 0x84C5
	// Texture6 as defined in GLES3/gl3.h:278
	Texture6 = 0x84C6
	// Texture7 as defined in GLES3/gl3.h:279
	Texture7 = 0x84C7
	// Texture8 as defined in GLES3/gl3.h:280
	Texture8 = 0x84C8
	// Texture9 as defined in GLES3/gl3.h:281
	Texture9 = 0x84C9
	// Texture10 as defined in GLES3/gl3.h:282
	Texture10 = 0x84CA
	// Texture11 as defined in GLES3/gl3.h:283
	Texture11 = 0x84CB
	// Texture12 as defined in GLES3/gl3.h:284
	Texture12 = 0x84CC
	// Texture13 as defined in GLES3/gl3.h:285
	Texture13 = 0x84CD
	// Texture14 as defined in GLES3/gl3.h:286
	Texture14 = 0x84CE
	// Texture15 as defined in GLES3/gl3.h:287
	Texture15 = 0x84CF
	// Texture16 as defined in GLES3/gl3.h:288
	Texture16 = 0x84D0
	// Texture17 as defined in GLES3/gl3.h:289
	Texture17 = 0x84D1
	// Texture18 as defined in GLES3/gl3.h:290
	Texture18 = 0x84D2
	// Texture19 as defined in GLES3/gl3.h:291
	Texture19 = 0x84D3
	// Texture20 as defined in GLES3/gl3.h:292
	Texture20 = 0x84D4
	// Texture21 as defined in GLES3/gl3.h:293
	Texture21 = 0x84D5
	// Texture22 as defined in GLES3/gl3.h:294
	Texture22 = 0x84D6
	// Texture23 as defined in GLES3/gl3.h:295
	Texture23 = 0x84D7
	// Texture24 as defined in GLES3/gl3.h:296
	Texture24 = 0x84D8
	// Texture25 as defined in GLES3/gl3.h:297
	Texture25 = 0x84D9
	// Texture26 as defined in GLES3/gl3.h:298
	Texture26 = 0x84DA
	// Texture27 as defined in GLES3/gl3.h:299
	Texture27 = 0x84DB
	// Texture28 as defined in GLES3/gl3.h:300
	Texture28 = 0x84DC
	// Texture29 as defined in GLES3/gl3.h:301
	Texture29 = 0x84DD
	// Texture30 as defined in GLES3/gl3.h:302
	Texture30 = 0x84DE
	// Texture31 as defined in GLES3/gl3.h:303
	Texture31 = 0x84DF
	// ActiveTexture as defined in GLES3/gl3.h:304
	ActiveTexture = 0x84E0
	// Repeat as defined in GLES3/gl3.h:305
	Repeat = 0x2901
	// ClampToEdge as defined in GLES3/gl3.h:306
	ClampToEdge = 0x812F
	// MirroredRepeat as defined in GLES3/gl3.h:307
	MirroredRepeat = 0x8370
	// FloatVec2 as defined in GLES3/gl3.h:308
	FloatVec2 = 0x8B50
	// FloatVec3 as defined in GLES3/gl3.h:309
	FloatVec3 = 0x8B51
	// FloatVec4 as defined in GLES3/gl3.h:310
	FloatVec4 = 0x8B52
	// IntVec2 as defined in GLES3/gl3.h:311
	IntVec2 = 0x8B53
	// IntVec3 as defined in GLES3/gl3.h:312
	IntVec3 = 0x8B54
	// IntVec4 as defined in GLES3/gl3.h:313
	IntVec4 = 0x8B55
	// Bool as defined in GLES3/gl3.h:314
	Bool = 0x8B56
	// BoolVec2 as defined in GLES3/gl3.h:315
	BoolVec2 = 0x8B57
	// BoolVec3 as defined in GLES3/gl3.h:316
	BoolVec3 = 0x8B58
	// BoolVec4 as defined in GLES3/gl3.h:317
	BoolVec4 = 0x8B59
	// FloatMat2 as defined in GLES3/gl3.h:318
	FloatMat2 = 0x8B5A
	// FloatMat3 as defined in GLES3/gl3.h:319
	FloatMat3 = 0x8B5B
	// FloatMat4 as defined in GLES3/gl3.h:320
	FloatMat4 = 0x8B5C
	// Sampler2d as defined in GLES3/gl3.h:321
	Sampler2d = 0x8B5E
	// SamplerCube as defined in GLES3/gl3.h:322
	SamplerCube = 0x8B60
	// VertexAttribArrayEnabled as defined in GLES3/gl3.h:323
	VertexAttribArrayEnabled = 0x8622
	// VertexAttribArraySize as defined in GLES3/gl3.h:324
	VertexAttribArraySize = 0x8623
	// VertexAttribArrayStride as defined in GLES3/gl3.h:325
	VertexAttribArrayStride = 0x8624
	// VertexAttribArrayType as defined in GLES3/gl3.h:326
	VertexAttribArrayType = 0x8625
	// VertexAttribArrayNormalized as defined in GLES3/gl3.h:327
	VertexAttribArrayNormalized = 0x886A
	// VertexAttribArrayPointer as defined in GLES3/gl3.h:328
	VertexAttribArrayPointer = 0x8645
	// VertexAttribArrayBufferBinding as defined in GLES3/gl3.h:329
	VertexAttribArrayBufferBinding = 0x889F
	// ImplementationColorReadType as defined in GLES3/gl3.h:330
	ImplementationColorReadType = 0x8B9A
	// ImplementationColorReadFormat as defined in GLES3/gl3.h:331
	ImplementationColorReadFormat = 0x8B9B
	// CompileStatus as defined in GLES3/gl3.h:332
	CompileStatus = 0x8B81
	// InfoLogLength as defined in GLES3/gl3.h:333
	InfoLogLength = 0x8B84
	// ShaderSourceLength as defined in GLES3/gl3.h:334
	ShaderSourceLength = 0x8B88
	// ShaderCompiler as defined in GLES3/gl3.h:335
	ShaderCompiler = 0x8DFA
	// ShaderBinaryFormats as defined in GLES3/gl3.h:336
	ShaderBinaryFormats = 0x8DF8
	// NumShaderBinaryFormats as defined in GLES3/gl3.h:337
	NumShaderBinaryFormats = 0x8DF9
	// LowFloatType as defined in GLES3/gl3.h:338
	LowFloatType = 0x8DF0
	// MediumFloatType as defined in GLES3/gl3.h:339
	MediumFloatType = 0x8DF1
	// HighFloatType as defined in GLES3/gl3.h:340
	HighFloatType = 0x8DF2
	// LowIntType as defined in GLES3/gl3.h:341
	LowIntType = 0x8DF3
	// MediumIntType as defined in GLES3/gl3.h:342
	MediumIntType = 0x8DF4
	// HighIntType as defined in GLES3/gl3.h:343
	HighIntType = 0x8DF5
	// Framebuffer as defined in GLES3/gl3.h:344
	Framebuffer = 0x8D40
	// Renderbuffer as defined in GLES3/gl3.h:345
	Renderbuffer = 0x8D41
	// Rgba4 as defined in GLES3/gl3.h:346
	Rgba4 = 0x8056
	// Rgb5A1 as defined in GLES3/gl3.h:347
	Rgb5A1 = 0x8057
	// Rgb565 as defined in GLES3/gl3.h:348
	Rgb565 = 0x8D62
	// DepthComponent16 as defined in GLES3/gl3.h:349
	DepthComponent16 = 0x81A5
	// StencilIndex8 as defined in GLES3/gl3.h:350
	StencilIndex8 = 0x8D48
	// RenderbufferWidth as defined in GLES3/gl3.h:351
	RenderbufferWidth = 0x8D42
	// RenderbufferHeight as defined in GLES3/gl3.h:352
	RenderbufferHeight = 0x8D43
	// RenderbufferInternalFormat as defined in GLES3/gl3.h:353
	RenderbufferInternalFormat = 0x8D44
	// RenderbufferRedSize as defined in GLES3/gl3.h:354
	RenderbufferRedSize = 0x8D50
	// RenderbufferGreenSize as defined in GLES3/gl3.h:355
	RenderbufferGreenSize = 0x8D51
	// RenderbufferBlueSize as defined in GLES3/gl3.h:356
	RenderbufferBlueSize = 0x8D52
	// RenderbufferAlphaSize as defined in GLES3/gl3.h:357
	RenderbufferAlphaSize = 0x8D53
	// RenderbufferDepthSize as defined in GLES3/gl3.h:358
	RenderbufferDepthSize = 0x8D54
	// RenderbufferStencilSize as defined in GLES3/gl3.h:359
	RenderbufferStencilSize = 0x8D55
	// FramebufferAttachmentObjectType as defined in GLES3/gl3.h:360
	FramebufferAttachmentObjectType = 0x8CD0
	// FramebufferAttachmentObjectName as defined in GLES3/gl3.h:361
	FramebufferAttachmentObjectName = 0x8CD1
	// FramebufferAttachmentTextureLevel as defined in GLES3/gl3.h:362
	FramebufferAttachmentTextureLevel = 0x8CD2
	// FramebufferAttachmentTextureCubeMapFace as defined in GLES3/gl3.h:363
	FramebufferAttachmentTextureCubeMapFace = 0x8CD3
	// ColorAttachment0 as defined in GLES3/gl3.h:364
	ColorAttachment0 = 0x8CE0
	// DepthAttachment as defined in GLES3/gl3.h:365
	DepthAttachment = 0x8D00
	// StencilAttachment as defined in GLES3/gl3.h:366
	StencilAttachment = 0x8D20
	// None as defined in GLES3/gl3.h:367
	None = 0
	// FramebufferComplete as defined in GLES3/gl3.h:368
	FramebufferComplete = 0x8CD5
	// FramebufferIncompleteAttachment as defined in GLES3/gl3.h:369
	FramebufferIncompleteAttachment = 0x8CD6
	// FramebufferIncompleteMissingAttachment as defined in GLES3/gl3.h:370
	FramebufferIncompleteMissingAttachment = 0x8CD7
	// FramebufferIncompleteDimensions as defined in GLES3/gl3.h:371
	FramebufferIncompleteDimensions = 0x8CD9
	// FramebufferUnsupported as defined in GLES3/gl3.h:372
	FramebufferUnsupported = 0x8CDD
	// FramebufferBinding as defined in GLES3/gl3.h:373
	FramebufferBinding = 0x8CA6
	// RenderbufferBinding as defined in GLES3/gl3.h:374
	RenderbufferBinding = 0x8CA7
	// MaxRenderbufferSize as defined in GLES3/gl3.h:375
	MaxRenderbufferSize = 0x84E8
	// InvalidFramebufferOperation as defined in GLES3/gl3.h:376
	InvalidFramebufferOperation = 0x0506
	// EsVersion30 as defined in GLES3/gl3.h:522
	EsVersion30 = 1
	// ReadBuffer as defined in GLES3/gl3.h:524
	ReadBuffer = 0x0C02
	// UnpackRowLength as defined in GLES3/gl3.h:525
	UnpackRowLength = 0x0CF2
	// UnpackSkipRows as defined in GLES3/gl3.h:526
	UnpackSkipRows = 0x0CF3
	// UnpackSkipPixels as defined in GLES3/gl3.h:527
	UnpackSkipPixels = 0x0CF4
	// PackRowLength as defined in GLES3/gl3.h:528
	PackRowLength = 0x0D02
	// PackSkipRows as defined in GLES3/gl3.h:529
	PackSkipRows = 0x0D03
	// PackSkipPixels as defined in GLES3/gl3.h:530
	PackSkipPixels = 0x0D04
	// Color as defined in GLES3/gl3.h:531
	Color = 0x1800
	// Depth as defined in GLES3/gl3.h:532
	Depth = 0x1801
	// Stencil as defined in GLES3/gl3.h:533
	Stencil = 0x1802
	// Red as defined in GLES3/gl3.h:534
	Red = 0x1903
	// Rgb8 as defined in GLES3/gl3.h:535
	Rgb8 = 0x8051
	// Rgba8 as defined in GLES3/gl3.h:536
	Rgba8 = 0x8058
	// Rgb10A2 as defined in GLES3/gl3.h:537
	Rgb10A2 = 0x8059
	// TextureBinding3d as defined in GLES3/gl3.h:538
	TextureBinding3d = 0x806A
	// UnpackSkipImages as defined in GLES3/gl3.h:539
	UnpackSkipImages = 0x806D
	// UnpackImageHeight as defined in GLES3/gl3.h:540
	UnpackImageHeight = 0x806E
	// Texture3d as defined in GLES3/gl3.h:541
	Texture3d = 0x806F
	// TextureWrapR as defined in GLES3/gl3.h:542
	TextureWrapR = 0x8072
	// Max3dTextureSize as defined in GLES3/gl3.h:543
	Max3dTextureSize = 0x8073
	// UnsignedInt2101010Rev as defined in GLES3/gl3.h:544
	UnsignedInt2101010Rev = 0x8368
	// MaxElementsVertices as defined in GLES3/gl3.h:545
	MaxElementsVertices = 0x80E8
	// MaxElementsIndices as defined in GLES3/gl3.h:546
	MaxElementsIndices = 0x80E9
	// TextureMinLod as defined in GLES3/gl3.h:547
	TextureMinLod = 0x813A
	// TextureMaxLod as defined in GLES3/gl3.h:548
	TextureMaxLod = 0x813B
	// TextureBaseLevel as defined in GLES3/gl3.h:549
	TextureBaseLevel = 0x813C
	// TextureMaxLevel as defined in GLES3/gl3.h:550
	TextureMaxLevel = 0x813D
	// Min as defined in GLES3/gl3.h:551
	Min = 0x8007
	// Max as defined in GLES3/gl3.h:552
	Max = 0x8008
	// DepthComponent24 as defined in GLES3/gl3.h:553
	DepthComponent24 = 0x81A6
	// MaxTextureLodBias as defined in GLES3/gl3.h:554
	MaxTextureLodBias = 0x84FD
	// TextureCompareMode as defined in GLES3/gl3.h:555
	TextureCompareMode = 0x884C
	// TextureCompareFunc as defined in GLES3/gl3.h:556
	TextureCompareFunc = 0x884D
	// CurrentQuery as defined in GLES3/gl3.h:557
	CurrentQuery = 0x8865
	// QueryResult as defined in GLES3/gl3.h:558
	QueryResult = 0x8866
	// QueryResultAvailable as defined in GLES3/gl3.h:559
	QueryResultAvailable = 0x8867
	// BufferMapped as defined in GLES3/gl3.h:560
	BufferMapped = 0x88BC
	// BufferMapPointer as defined in GLES3/gl3.h:561
	BufferMapPointer = 0x88BD
	// StreamRead as defined in GLES3/gl3.h:562
	StreamRead = 0x88E1
	// StreamCopy as defined in GLES3/gl3.h:563
	StreamCopy = 0x88E2
	// StaticRead as defined in GLES3/gl3.h:564
	StaticRead = 0x88E5
	// StaticCopy as defined in GLES3/gl3.h:565
	StaticCopy = 0x88E6
	// DynamicRead as defined in GLES3/gl3.h:566
	DynamicRead = 0x88E9
	// DynamicCopy as defined in GLES3/gl3.h:567
	DynamicCopy = 0x88EA
	// MaxDrawBuffers as defined in GLES3/gl3.h:568
	MaxDrawBuffers = 0x8824
	// DrawBuffer0 as defined in GLES3/gl3.h:569
	DrawBuffer0 = 0x8825
	// DrawBuffer1 as defined in GLES3/gl3.h:570
	DrawBuffer1 = 0x8826
	// DrawBuffer2 as defined in GLES3/gl3.h:571
	DrawBuffer2 = 0x8827
	// DrawBuffer3 as defined in GLES3/gl3.h:572
	DrawBuffer3 = 0x8828
	// DrawBuffer4 as defined in GLES3/gl3.h:573
	DrawBuffer4 = 0x8829
	// DrawBuffer5 as defined in GLES3/gl3.h:574
	DrawBuffer5 = 0x882A
	// DrawBuffer6 as defined in GLES3/gl3.h:575
	DrawBuffer6 = 0x882B
	// DrawBuffer7 as defined in GLES3/gl3.h:576
	DrawBuffer7 = 0x882C
	// DrawBuffer8 as defined in GLES3/gl3.h:577
	DrawBuffer8 = 0x882D
	// DrawBuffer9 as defined in GLES3/gl3.h:578
	DrawBuffer9 = 0x882E
	// DrawBuffer10 as defined in GLES3/gl3.h:579
	DrawBuffer10 = 0x882F
	// DrawBuffer11 as defined in GLES3/gl3.h:580
	DrawBuffer11 = 0x8830
	// DrawBuffer12 as defined in GLES3/gl3.h:581
	DrawBuffer12 = 0x8831
	// DrawBuffer13 as defined in GLES3/gl3.h:582
	DrawBuffer13 = 0x8832
	// DrawBuffer14 as defined in GLES3/gl3.h:583
	DrawBuffer14 = 0x8833
	// DrawBuffer15 as defined in GLES3/gl3.h:584
	DrawBuffer15 = 0x8834
	// MaxFragmentUniformComponents as defined in GLES3/gl3.h:585
	MaxFragmentUniformComponents = 0x8B49
	// MaxVertexUniformComponents as defined in GLES3/gl3.h:586
	MaxVertexUniformComponents = 0x8B4A
	// Sampler3d as defined in GLES3/gl3.h:587
	Sampler3d = 0x8B5F
	// Sampler2dShadow as defined in GLES3/gl3.h:588
	Sampler2dShadow = 0x8B62
	// FragmentShaderDerivativeHintType as defined in GLES3/gl3.h:589
	FragmentShaderDerivativeHintType = 0x8B8B
	// PixelPackBuffer as defined in GLES3/gl3.h:590
	PixelPackBuffer = 0x88EB
	// PixelUnpackBuffer as defined in GLES3/gl3.h:591
	PixelUnpackBuffer = 0x88EC
	// PixelPackBufferBinding as defined in GLES3/gl3.h:592
	PixelPackBufferBinding = 0x88ED
	// PixelUnpackBufferBinding as defined in GLES3/gl3.h:593
	PixelUnpackBufferBinding = 0x88EF
	// FloatMat2x3 as defined in GLES3/gl3.h:594
	FloatMat2x3 = 0x8B65
	// FloatMat2x4 as defined in GLES3/gl3.h:595
	FloatMat2x4 = 0x8B66
	// FloatMat3x2 as defined in GLES3/gl3.h:596
	FloatMat3x2 = 0x8B67
	// FloatMat3x4 as defined in GLES3/gl3.h:597
	FloatMat3x4 = 0x8B68
	// FloatMat4x2 as defined in GLES3/gl3.h:598
	FloatMat4x2 = 0x8B69
	// FloatMat4x3 as defined in GLES3/gl3.h:599
	FloatMat4x3 = 0x8B6A
	// Srgb as defined in GLES3/gl3.h:600
	Srgb = 0x8C40
	// Srgb8 as defined in GLES3/gl3.h:601
	Srgb8 = 0x8C41
	// Srgb8Alpha8 as defined in GLES3/gl3.h:602
	Srgb8Alpha8 = 0x8C43
	// CompareRefToTexture as defined in GLES3/gl3.h:603
	CompareRefToTexture = 0x884E
	// MajorVersion as defined in GLES3/gl3.h:604
	MajorVersion = 0x821B
	// MinorVersion as defined in GLES3/gl3.h:605
	MinorVersion = 0x821C
	// NumExtensions as defined in GLES3/gl3.h:606
	NumExtensions = 0x821D
	// Rgba32f as defined in GLES3/gl3.h:607
	Rgba32f = 0x8814
	// Rgb32f as defined in GLES3/gl3.h:608
	Rgb32f = 0x8815
	// Rgba16f as defined in GLES3/gl3.h:609
	Rgba16f = 0x881A
	// Rgb16f as defined in GLES3/gl3.h:610
	Rgb16f = 0x881B
	// VertexAttribArrayInteger as defined in GLES3/gl3.h:611
	VertexAttribArrayInteger = 0x88FD
	// MaxArrayTextureLayers as defined in GLES3/gl3.h:612
	MaxArrayTextureLayers = 0x88FF
	// MinProgramTexelOffset as defined in GLES3/gl3.h:613
	MinProgramTexelOffset = 0x8904
	// MaxProgramTexelOffset as defined in GLES3/gl3.h:614
	MaxProgramTexelOffset = 0x8905
	// MaxVaryingComponents as defined in GLES3/gl3.h:615
	MaxVaryingComponents = 0x8B4B
	// Texture2dArray as defined in GLES3/gl3.h:616
	Texture2dArray = 0x8C1A
	// TextureBinding2dArray as defined in GLES3/gl3.h:617
	TextureBinding2dArray = 0x8C1D
	// R11fG11fB10f as defined in GLES3/gl3.h:618
	R11fG11fB10f = 0x8C3A
	// UnsignedInt10f11f11fRev as defined in GLES3/gl3.h:619
	UnsignedInt10f11f11fRev = 0x8C3B
	// Rgb9E5 as defined in GLES3/gl3.h:620
	Rgb9E5 = 0x8C3D
	// UnsignedInt5999Rev as defined in GLES3/gl3.h:621
	UnsignedInt5999Rev = 0x8C3E
	// TransformFeedbackVaryingMaxLength as defined in GLES3/gl3.h:622
	TransformFeedbackVaryingMaxLength = 0x8C76
	// TransformFeedbackBufferMode as defined in GLES3/gl3.h:623
	TransformFeedbackBufferMode = 0x8C7F
	// MaxTransformFeedbackSeparateComponents as defined in GLES3/gl3.h:624
	MaxTransformFeedbackSeparateComponents = 0x8C80
	// TransformFeedbackVaryings as defined in GLES3/gl3.h:625
	TransformFeedbackVaryings = 0x8C83
	// TransformFeedbackBufferStart as defined in GLES3/gl3.h:626
	TransformFeedbackBufferStart = 0x8C84
	// TransformFeedbackBufferSize as defined in GLES3/gl3.h:627
	TransformFeedbackBufferSize = 0x8C85
	// TransformFeedbackPrimitivesWritten as defined in GLES3/gl3.h:628
	TransformFeedbackPrimitivesWritten = 0x8C88
	// RasterizerDiscard as defined in GLES3/gl3.h:629
	RasterizerDiscard = 0x8C89
	// MaxTransformFeedbackInterleavedComponents as defined in GLES3/gl3.h:630
	MaxTransformFeedbackInterleavedComponents = 0x8C8A
	// MaxTransformFeedbackSeparateAttribs as defined in GLES3/gl3.h:631
	MaxTransformFeedbackSeparateAttribs = 0x8C8B
	// InterleavedAttribs as defined in GLES3/gl3.h:632
	InterleavedAttribs = 0x8C8C
	// SeparateAttribs as defined in GLES3/gl3.h:633
	SeparateAttribs = 0x8C8D
	// TransformFeedbackBuffer as defined in GLES3/gl3.h:634
	TransformFeedbackBuffer = 0x8C8E
	// TransformFeedbackBufferBinding as defined in GLES3/gl3.h:635
	TransformFeedbackBufferBinding = 0x8C8F
	// Rgba32ui as defined in GLES3/gl3.h:636
	Rgba32ui = 0x8D70
	// Rgb32ui as defined in GLES3/gl3.h:637
	Rgb32ui = 0x8D71
	// Rgba16ui as defined in GLES3/gl3.h:638
	Rgba16ui = 0x8D76
	// Rgb16ui as defined in GLES3/gl3.h:639
	Rgb16ui = 0x8D77
	// Rgba8ui as defined in GLES3/gl3.h:640
	Rgba8ui = 0x8D7C
	// Rgb8ui as defined in GLES3/gl3.h:641
	Rgb8ui = 0x8D7D
	// Rgba32i as defined in GLES3/gl3.h:642
	Rgba32i = 0x8D82
	// Rgb32i as defined in GLES3/gl3.h:643
	Rgb32i = 0x8D83
	// Rgba16i as defined in GLES3/gl3.h:644
	Rgba16i = 0x8D88
	// Rgb16i as defined in GLES3/gl3.h:645
	Rgb16i = 0x8D89
	// Rgba8i as defined in GLES3/gl3.h:646
	Rgba8i = 0x8D8E
	// Rgb8i as defined in GLES3/gl3.h:647
	Rgb8i = 0x8D8F
	// RedInteger as defined in GLES3/gl3.h:648
	RedInteger = 0x8D94
	// RgbInteger as defined in GLES3/gl3.h:649
	RgbInteger = 0x8D98
	// RgbaInteger as defined in GLES3/gl3.h:650
	RgbaInteger = 0x8D99
	// Sampler2dArray as defined in GLES3/gl3.h:651
	Sampler2dArray = 0x8DC1
	// Sampler2dArrayShadow as defined in GLES3/gl3.h:652
	Sampler2dArrayShadow = 0x8DC4
	// SamplerCubeShadow as defined in GLES3/gl3.h:653
	SamplerCubeShadow = 0x8DC5
	// UnsignedIntVec2 as defined in GLES3/gl3.h:654
	UnsignedIntVec2 = 0x8DC6
	// UnsignedIntVec3 as defined in GLES3/gl3.h:655
	UnsignedIntVec3 = 0x8DC7
	// UnsignedIntVec4 as defined in GLES3/gl3.h:656
	UnsignedIntVec4 = 0x8DC8
	// IntSampler2d as defined in GLES3/gl3.h:657
	IntSampler2d = 0x8DCA
	// IntSampler3d as defined in GLES3/gl3.h:658
	IntSampler3d = 0x8DCB
	// IntSamplerCube as defined in GLES3/gl3.h:659
	IntSamplerCube = 0x8DCC
	// IntSampler2dArray as defined in GLES3/gl3.h:660
	IntSampler2dArray = 0x8DCF
	// UnsignedIntSampler2d as defined in GLES3/gl3.h:661
	UnsignedIntSampler2d = 0x8DD2
	// UnsignedIntSampler3d as defined in GLES3/gl3.h:662
	UnsignedIntSampler3d = 0x8DD3
	// UnsignedIntSamplerCube as defined in GLES3/gl3.h:663
	UnsignedIntSamplerCube = 0x8DD4
	// UnsignedIntSampler2dArray as defined in GLES3/gl3.h:664
	UnsignedIntSampler2dArray = 0x8DD7
	// BufferAccessFlags as defined in GLES3/gl3.h:665
	BufferAccessFlags = 0x911F
	// BufferMapLength as defined in GLES3/gl3.h:666
	BufferMapLength = 0x9120
	// BufferMapOffset as defined in GLES3/gl3.h:667
	BufferMapOffset = 0x9121
	// DepthComponent32f as defined in GLES3/gl3.h:668
	DepthComponent32f = 0x8CAC
	// Depth32fStencil8 as defined in GLES3/gl3.h:669
	Depth32fStencil8 = 0x8CAD
	// Float32UnsignedInt248Rev as defined in GLES3/gl3.h:670
	Float32UnsignedInt248Rev = 0x8DAD
	// FramebufferAttachmentColorEncoding as defined in GLES3/gl3.h:671
	FramebufferAttachmentColorEncoding = 0x8210
	// FramebufferAttachmentComponentType as defined in GLES3/gl3.h:672
	FramebufferAttachmentComponentType = 0x8211
	// FramebufferAttachmentRedSize as defined in GLES3/gl3.h:673
	FramebufferAttachmentRedSize = 0x8212
	// FramebufferAttachmentGreenSize as defined in GLES3/gl3.h:674
	FramebufferAttachmentGreenSize = 0x8213
	// FramebufferAttachmentBlueSize as defined in GLES3/gl3.h:675
	FramebufferAttachmentBlueSize = 0x8214
	// FramebufferAttachmentAlphaSize as defined in GLES3/gl3.h:676
	FramebufferAttachmentAlphaSize = 0x8215
	// FramebufferAttachmentDepthSize as defined in GLES3/gl3.h:677
	FramebufferAttachmentDepthSize = 0x8216
	// FramebufferAttachmentStencilSize as defined in GLES3/gl3.h:678
	FramebufferAttachmentStencilSize = 0x8217
	// FramebufferDefault as defined in GLES3/gl3.h:679
	FramebufferDefault = 0x8218
	// FramebufferUndefined as defined in GLES3/gl3.h:680
	FramebufferUndefined = 0x8219
	// DepthStencilAttachment as defined in GLES3/gl3.h:681
	DepthStencilAttachment = 0x821A
	// DepthStencil as defined in GLES3/gl3.h:682
	DepthStencil = 0x84F9
	// UnsignedInt248 as defined in GLES3/gl3.h:683
	UnsignedInt248 = 0x84FA
	// Depth24Stencil8 as defined in GLES3/gl3.h:684
	Depth24Stencil8 = 0x88F0
	// UnsignedNormalized as defined in GLES3/gl3.h:685
	UnsignedNormalized = 0x8C17
	// DrawFramebufferBinding as defined in GLES3/gl3.h:686
	DrawFramebufferBinding = 0x8CA6
	// ReadFramebuffer as defined in GLES3/gl3.h:687
	ReadFramebuffer = 0x8CA8
	// DrawFramebuffer as defined in GLES3/gl3.h:688
	DrawFramebuffer = 0x8CA9
	// ReadFramebufferBinding as defined in GLES3/gl3.h:689
	ReadFramebufferBinding = 0x8CAA
	// RenderbufferSamples as defined in GLES3/gl3.h:690
	RenderbufferSamples = 0x8CAB
	// FramebufferAttachmentTextureLayer as defined in GLES3/gl3.h:691
	FramebufferAttachmentTextureLayer = 0x8CD4
	// MaxColorAttachments as defined in GLES3/gl3.h:692
	MaxColorAttachments = 0x8CDF
	// ColorAttachment1 as defined in GLES3/gl3.h:693
	ColorAttachment1 = 0x8CE1
	// ColorAttachment2 as defined in GLES3/gl3.h:694
	ColorAttachment2 = 0x8CE2
	// ColorAttachment3 as defined in GLES3/gl3.h:695
	ColorAttachment3 = 0x8CE3
	// ColorAttachment4 as defined in GLES3/gl3.h:696
	ColorAttachment4 = 0x8CE4
	// ColorAttachment5 as defined in GLES3/gl3.h:697
	ColorAttachment5 = 0x8CE5
	// ColorAttachment6 as defined in GLES3/gl3.h:698
	ColorAttachment6 = 0x8CE6
	// ColorAttachment7 as defined in GLES3/gl3.h:699
	ColorAttachment7 = 0x8CE7
	// ColorAttachment8 as defined in GLES3/gl3.h:700
	ColorAttachment8 = 0x8CE8
	// ColorAttachment9 as defined in GLES3/gl3.h:701
	ColorAttachment9 = 0x8CE9
	// ColorAttachment10 as defined in GLES3/gl3.h:702
	ColorAttachment10 = 0x8CEA
	// ColorAttachment11 as defined in GLES3/gl3.h:703
	ColorAttachment11 = 0x8CEB
	// ColorAttachment12 as defined in GLES3/gl3.h:704
	ColorAttachment12 = 0x8CEC
	// ColorAttachment13 as defined in GLES3/gl3.h:705
	ColorAttachment13 = 0x8CED
	// ColorAttachment14 as defined in GLES3/gl3.h:706
	ColorAttachment14 = 0x8CEE
	// ColorAttachment15 as defined in GLES3/gl3.h:707
	ColorAttachment15 = 0x8CEF
	// FramebufferIncompleteMultisample as defined in GLES3/gl3.h:708
	FramebufferIncompleteMultisample = 0x8D56
	// MaxSamples as defined in GLES3/gl3.h:709
	MaxSamples = 0x8D57
	// HalfFloatType as defined in GLES3/gl3.h:710
	HalfFloatType = 0x140B
	// MapReadBit as defined in GLES3/gl3.h:711
	MapReadBit = 0x0001
	// MapWriteBit as defined in GLES3/gl3.h:712
	MapWriteBit = 0x0002
	// MapInvalidateRangeBit as defined in GLES3/gl3.h:713
	MapInvalidateRangeBit = 0x0004
	// MapInvalidateBufferBit as defined in GLES3/gl3.h:714
	MapInvalidateBufferBit = 0x0008
	// MapFlushExplicitBit as defined in GLES3/gl3.h:715
	MapFlushExplicitBit = 0x0010
	// MapUnsynchronizedBit as defined in GLES3/gl3.h:716
	MapUnsynchronizedBit = 0x0020
	// Rg as defined in GLES3/gl3.h:717
	Rg = 0x8227
	// RgInteger as defined in GLES3/gl3.h:718
	RgInteger = 0x8228
	// R8 as defined in GLES3/gl3.h:719
	R8 = 0x8229
	// Rg8 as defined in GLES3/gl3.h:720
	Rg8 = 0x822B
	// R16f as defined in GLES3/gl3.h:721
	R16f = 0x822D
	// R32f as defined in GLES3/gl3.h:722
	R32f = 0x822E
	// Rg16f as defined in GLES3/gl3.h:723
	Rg16f = 0x822F
	// Rg32f as defined in GLES3/gl3.h:724
	Rg32f = 0x8230
	// R8i as defined in GLES3/gl3.h:725
	R8i = 0x8231
	// R8ui as defined in GLES3/gl3.h:726
	R8ui = 0x8232
	// R16i as defined in GLES3/gl3.h:727
	R16i = 0x8233
	// R16ui as defined in GLES3/gl3.h:728
	R16ui = 0x8234
	// R32i as defined in GLES3/gl3.h:729
	R32i = 0x8235
	// R32ui as defined in GLES3/gl3.h:730
	R32ui = 0x8236
	// Rg8i as defined in GLES3/gl3.h:731
	Rg8i = 0x8237
	// Rg8ui as defined in GLES3/gl3.h:732
	Rg8ui = 0x8238
	// Rg16i as defined in GLES3/gl3.h:733
	Rg16i = 0x8239
	// Rg16ui as defined in GLES3/gl3.h:734
	Rg16ui = 0x823A
	// Rg32i as defined in GLES3/gl3.h:735
	Rg32i = 0x823B
	// Rg32ui as defined in GLES3/gl3.h:736
	Rg32ui = 0x823C
	// VertexArrayBinding as defined in GLES3/gl3.h:737
	VertexArrayBinding = 0x85B5
	// R8Snorm as defined in GLES3/gl3.h:738
	R8Snorm = 0x8F94
	// Rg8Snorm as defined in GLES3/gl3.h:739
	Rg8Snorm = 0x8F95
	// Rgb8Snorm as defined in GLES3/gl3.h:740
	Rgb8Snorm = 0x8F96
	// Rgba8Snorm as defined in GLES3/gl3.h:741
	Rgba8Snorm = 0x8F97
	// SignedNormalized as defined in GLES3/gl3.h:742
	SignedNormalized = 0x8F9C
	// PrimitiveRestartFixedIndex as defined in GLES3/gl3.h:743
	PrimitiveRestartFixedIndex = 0x8D69
	// CopyReadBuffer as defined in GLES3/gl3.h:744
	CopyReadBuffer = 0x8F36
	// CopyWriteBuffer as defined in GLES3/gl3.h:745
	CopyWriteBuffer = 0x8F37
	// CopyReadBufferBinding as defined in GLES3/gl3.h:746
	CopyReadBufferBinding = 0x8F36
	// CopyWriteBufferBinding as defined in GLES3/gl3.h:747
	CopyWriteBufferBinding = 0x8F37
	// UniformBuffer as defined in GLES3/gl3.h:748
	UniformBuffer = 0x8A11
	// UniformBufferBinding as defined in GLES3/gl3.h:749
	UniformBufferBinding = 0x8A28
	// UniformBufferStart as defined in GLES3/gl3.h:750
	UniformBufferStart = 0x8A29
	// UniformBufferSize as defined in GLES3/gl3.h:751
	UniformBufferSize = 0x8A2A
	// MaxVertexUniformBlocks as defined in GLES3/gl3.h:752
	MaxVertexUniformBlocks = 0x8A2B
	// MaxFragmentUniformBlocks as defined in GLES3/gl3.h:753
	MaxFragmentUniformBlocks = 0x8A2D
	// MaxCombinedUniformBlocks as defined in GLES3/gl3.h:754
	MaxCombinedUniformBlocks = 0x8A2E
	// MaxUniformBufferBindings as defined in GLES3/gl3.h:755
	MaxUniformBufferBindings = 0x8A2F
	// MaxUniformBlockSize as defined in GLES3/gl3.h:756
	MaxUniformBlockSize = 0x8A30
	// MaxCombinedVertexUniformComponents as defined in GLES3/gl3.h:757
	MaxCombinedVertexUniformComponents = 0x8A31
	// MaxCombinedFragmentUniformComponents as defined in GLES3/gl3.h:758
	MaxCombinedFragmentUniformComponents = 0x8A33
	// UniformBufferOffsetAlignment as defined in GLES3/gl3.h:759
	UniformBufferOffsetAlignment = 0x8A34
	// ActiveUniformBlockMaxNameLength as defined in GLES3/gl3.h:760
	ActiveUniformBlockMaxNameLength = 0x8A35
	// ActiveUniformBlocks as defined in GLES3/gl3.h:761
	ActiveUniformBlocks = 0x8A36
	// UniformType as defined in GLES3/gl3.h:762
	UniformType = 0x8A37
	// UniformSize as defined in GLES3/gl3.h:763
	UniformSize = 0x8A38
	// UniformNameLength as defined in GLES3/gl3.h:764
	UniformNameLength = 0x8A39
	// UniformBlockIndex as defined in GLES3/gl3.h:765
	UniformBlockIndex = 0x8A3A
	// UniformOffset as defined in GLES3/gl3.h:766
	UniformOffset = 0x8A3B
	// UniformArrayStride as defined in GLES3/gl3.h:767
	UniformArrayStride = 0x8A3C
	// UniformMatrixStride as defined in GLES3/gl3.h:768
	UniformMatrixStride = 0x8A3D
	// UniformIsRowMajor as defined in GLES3/gl3.h:769
	UniformIsRowMajor = 0x8A3E
	// UniformBlockBinding as defined in GLES3/gl3.h:770
	UniformBlockBinding = 0x8A3F
	// UniformBlockDataSize as defined in GLES3/gl3.h:771
	UniformBlockDataSize = 0x8A40
	// UniformBlockNameLength as defined in GLES3/gl3.h:772
	UniformBlockNameLength = 0x8A41
	// UniformBlockActiveUniforms as defined in GLES3/gl3.h:773
	UniformBlockActiveUniforms = 0x8A42
	// UniformBlockActiveUniformIndices as defined in GLES3/gl3.h:774
	UniformBlockActiveUniformIndices = 0x8A43
	// UniformBlockReferencedByVertexShader as defined in GLES3/gl3.h:775
	UniformBlockReferencedByVertexShader = 0x8A44
	// UniformBlockReferencedByFragmentShader as defined in GLES3/gl3.h:776
	UniformBlockReferencedByFragmentShader = 0x8A46
	// InvalidIndex as defined in GLES3/gl3.h:777
	InvalidIndex = uint32(0xFFFFFFFF)
	// MaxVertexOutputComponents as defined in GLES3/gl3.h:778
	MaxVertexOutputComponents = 0x9122
	// MaxFragmentInputComponents as defined in GLES3/gl3.h:779
	MaxFragmentInputComponents = 0x9125
	// MaxServerWaitTimeout as defined in GLES3/gl3.h:780
	MaxServerWaitTimeout = 0x9111
	// ObjectType as defined in GLES3/gl3.h:781
	ObjectType = 0x9112
	// SyncCondition as defined in GLES3/gl3.h:782
	SyncCondition = 0x9113
	// SyncStatus as defined in GLES3/gl3.h:783
	SyncStatus = 0x9114
	// SyncFlags as defined in GLES3/gl3.h:784
	SyncFlags = 0x9115
	// SyncFence as defined in GLES3/gl3.h:785
	SyncFence = 0x9116
	// SyncGpuCommandsComplete as defined in GLES3/gl3.h:786
	SyncGpuCommandsComplete = 0x9117
	// Unsignaled as defined in GLES3/gl3.h:787
	Unsignaled = 0x9118
	// Signaled as defined in GLES3/gl3.h:788
	Signaled = 0x9119
	// AlreadySignaled as defined in GLES3/gl3.h:789
	AlreadySignaled = 0x911A
	// TimeoutExpired as defined in GLES3/gl3.h:790
	TimeoutExpired = 0x911B
	// ConditionSatisfied as defined in GLES3/gl3.h:791
	ConditionSatisfied = 0x911C
	// WaitFailed as defined in GLES3/gl3.h:792
	WaitFailed = 0x911D
	// SyncFlushCommandsBit as defined in GLES3/gl3.h:793
	SyncFlushCommandsBit = 0x00000001
	// TimeoutIgnored as defined in GLES3/gl3.h:794
	TimeoutIgnored = uint64(0xFFFFFFFFFFFFFFFF)
	// VertexAttribArrayDivisor as defined in GLES3/gl3.h:795
	VertexAttribArrayDivisor = 0x88FE
	// AnySamplesPassed as defined in GLES3/gl3.h:796
	AnySamplesPassed = 0x8C2F
	// AnySamplesPassedConservative as defined in GLES3/gl3.h:797
	AnySamplesPassedConservative = 0x8D6A
	// SamplerBinding as defined in GLES3/gl3.h:798
	SamplerBinding = 0x8919
	// Rgb10A2ui as defined in GLES3/gl3.h:799
	Rgb10A2ui = 0x906F
	// TextureSwizzleR as defined in GLES3/gl3.h:800
	TextureSwizzleR = 0x8E42
	// TextureSwizzleG as defined in GLES3/gl3.h:801
	TextureSwizzleG = 0x8E43
	// TextureSwizzleB as defined in GLES3/gl3.h:802
	TextureSwizzleB = 0x8E44
	// TextureSwizzleA as defined in GLES3/gl3.h:803
	TextureSwizzleA = 0x8E45
	// Green as defined in GLES3/gl3.h:804
	Green = 0x1904
	// Blue as defined in GLES3/gl3.h:805
	Blue = 0x1905
	// Int2101010Rev as defined in GLES3/gl3.h:806
	Int2101010Rev = 0x8D9F
	// TransformFeedback as defined in GLES3/gl3.h:807
	TransformFeedback = 0x8E22
	// TransformFeedbackPaused as defined in GLES3/gl3.h:808
	TransformFeedbackPaused = 0x8E23
	// TransformFeedbackActive as defined in GLES3/gl3.h:809
	TransformFeedbackActive = 0x8E24
	// TransformFeedbackBinding as defined in GLES3/gl3.h:810
	TransformFeedbackBinding = 0x8E25
	// ProgramBinaryRetrievableHintType as defined in GLES3/gl3.h:811
	ProgramBinaryRetrievableHintType = 0x8257
	// ProgramBinaryLength as defined in GLES3/gl3.h:812
	ProgramBinaryLength = 0x8741
	// NumProgramBinaryFormats as defined in GLES3/gl3.h:813
	NumProgramBinaryFormats = 0x87FE
	// ProgramBinaryFormats as defined in GLES3/gl3.h:814
	ProgramBinaryFormats = 0x87FF
	// CompressedR11Eac as defined in GLES3/gl3.h:815
	CompressedR11Eac = 0x9270
	// CompressedSignedR11Eac as defined in GLES3/gl3.h:816
	CompressedSignedR11Eac = 0x9271
	// CompressedRg11Eac as defined in GLES3/gl3.h:817
	CompressedRg11Eac = 0x9272
	// CompressedSignedRg11Eac as defined in GLES3/gl3.h:818
	CompressedSignedRg11Eac = 0x9273
	// CompressedRgb8Etc2 as defined in GLES3/gl3.h:819
	CompressedRgb8Etc2 = 0x9274
	// CompressedSrgb8Etc2 as defined in GLES3/gl3.h:820
	CompressedSrgb8Etc2 = 0x9275
	// CompressedRgb8PunchthroughAlpha1Etc2 as defined in GLES3/gl3.h:821
	CompressedRgb8PunchthroughAlpha1Etc2 = 0x9276
	// CompressedSrgb8PunchthroughAlpha1Etc2 as defined in GLES3/gl3.h:822
	CompressedSrgb8PunchthroughAlpha1Etc2 = 0x9277
	// CompressedRgba8Etc2Eac as defined in GLES3/gl3.h:823
	CompressedRgba8Etc2Eac = 0x9278
	// CompressedSrgb8Alpha8Etc2Eac as defined in GLES3/gl3.h:824
	CompressedSrgb8Alpha8Etc2Eac = 0x9279
	// TextureImmutableFormat as defined in GLES3/gl3.h:825
	TextureImmutableFormat = 0x912F
	// MaxElementIndex as defined in GLES3/gl3.h:826
	MaxElementIndex = 0x8D6B
	// NumSampleCounts as defined in GLES3/gl3.h:827
	NumSampleCounts = 0x9380
	// TextureImmutableLevels as defined in GLES3/gl3.h:828
	TextureImmutableLevels = 0x82DF
)
