// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Jan 2017 23:24:01 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package gles3 provides Go bindings for the OpenGL ES v3 API.
*/
package gles3
