// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 04 Jul 2017 10:30:16 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package gles3 provides Go bindings for the OpenGL ES v3 API.
*/
package gles3
