// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Jan 2017 23:39:25 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package gles3 provides Go bindings for the OpenGL ES v3 API.
*/
package gles3
