// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 25 May 2016 04:48:40 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int ALooper_callbackFunc_7e6b484c(int fd, int events, void* data) {
	return looperCallbackFunc7E6B484C(fd, events, data);
}

void ANativeActivity_createFunc_76dce4(ANativeActivity* activity, void* savedState, unsigned int savedStateSize) {
	nativeActivityCreateFunc76DCE4(activity, savedState, savedStateSize);
}

void AStorageManager_obbCallbackFunc_e8b15c3e(char* filename, int state, void* data) {
	storageManagerObbCallbackFuncE8B15C3E(filename, state, data);
}

