// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 16 Aug 2016 01:04:08 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package android provides Go bindings for the Android NDK API.
*/
package android
