// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Jan 2017 23:23:58 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package android provides Go bindings for the Android NDK API.
*/
package android
