// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 17 May 2016 04:44:23 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package android provides Go bindings for Android ABI.
*/
package android
