// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 17 May 2016 04:44:23 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package android

/*
#cgo LDFLAGS: -landroid
#include <android/api-level.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/input.h>
#include <android/keycodes.h>
#include <android/log.h>
#include <android/looper.h>
#include <android/native_activity.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <android/obb.h>
#include <android/rect.h>
#include <android/storage_manager.h>
#include <android/tts.h>
#include <android/window.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// AssetManager as declared in android/asset_manager.h:28
type AssetManager C.AAssetManager

// AssetDir as declared in android/asset_manager.h:31
type AssetDir C.AAssetDir

// Asset as declared in android/asset_manager.h:34
type Asset C.AAsset

// JNINativeMethod as declared in include/jni.h:147
type JNINativeMethod struct {
	name           string
	signature      string
	fnPtr          unsafe.Pointer
	refd6f16615    *C.JNINativeMethod
	allocsd6f16615 interface{}
}

// JNIEnv as declared in include/jni.h:157
type JNIEnv C.JNIEnv

// JavaVM as declared in include/jni.h:158
type JavaVM C.JavaVM

// JavaVMAttachArgs as declared in include/jni.h:1106
type JavaVMAttachArgs C.JavaVMAttachArgs

// JavaVMOption as declared in include/jni.h:1115
type JavaVMOption struct {
	optionString   string
	extraInfo      unsafe.Pointer
	refdae9fae3    *C.JavaVMOption
	allocsdae9fae3 interface{}
}

// JavaVMInitArgs as declared in include/jni.h:1123
type JavaVMInitArgs struct {
	version            int32
	nOptions           int32
	options            []JavaVMOption
	ignoreUnrecognized byte
	ref93580a6         *C.JavaVMInitArgs
	allocs93580a6      interface{}
}

// Looper as declared in android/looper.h:39
type Looper C.ALooper

// LooperCallbackFunc type as declared in android/looper.h:159
type LooperCallbackFunc func(fd int32, events int32, data unsafe.Pointer) int32

// NativeActivity as declared in android/native_activity.h:108
type NativeActivity C.ANativeActivity

// NativeActivityCallbacks as declared in android/native_activity.h:225
type NativeActivityCallbacks C.ANativeActivityCallbacks

// NativeActivityCreateFunc type as declared in android/native_activity.h:235
type NativeActivityCreateFunc func(activity *NativeActivity, savedState unsafe.Pointer, savedStateSize uint32)

// InputEvent as declared in android/input.h:136
type InputEvent C.AInputEvent

// InputQueue as declared in android/input.h:803
type InputQueue C.AInputQueue

// NativeWindow as declared in android/native_window.h:36
type NativeWindow C.ANativeWindow

// NativeWindowBuffer as declared in android/native_window.h:57
type NativeWindowBuffer struct {
	width          int32
	height         int32
	stride         int32
	format         int32
	bits           unsafe.Pointer
	reserved       [6]uint32
	ref3db2646c    *C.ANativeWindow_Buffer
	allocs3db2646c interface{}
}

// Rect as declared in android/rect.h:35
type Rect struct {
	left           int32
	top            int32
	right          int32
	bottom         int32
	ref9511c547    *C.ARect
	allocs9511c547 interface{}
}

// ObbInfo as declared in android/obb.h:28
type ObbInfo C.AObbInfo

// StorageManager as declared in android/storage_manager.h:28
type StorageManager C.AStorageManager

// StorageManagerObbCallbackFunc type as declared in android/storage_manager.h:98
type StorageManagerObbCallbackFunc func(filename string, state int32, data unsafe.Pointer)
