// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 22 Sep 2016 02:15:07 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include <GLES/gl.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

