// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 04 Sep 2016 02:35:43 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include <GLES/gl.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

