// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 16 Aug 2016 01:17:47 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package gles provides Go bindings for the OpenGL ES v1 API.
*/
package gles
