// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 28 May 2016 05:14:17 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package gles provides Go bindings for the OpenGL ES v1 API.
*/
package gles
