// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:50:45 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package gles provides Go bindings for the OpenGL ES v1 API.
*/
package gles
