// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Jan 2017 23:24:00 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package gles

/*
#cgo LDFLAGS: -lGLESv1_CM
#include <GLES/gl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// AlphaFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glAlphaFunc.xml
func AlphaFunc(_func uint32, ref float32) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLclampf)(ref), cgoAllocsUnknown
	C.glAlphaFunc(c_func, cref)
}

// ClearColor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearColor.xml
func ClearColor(red float32, green float32, blue float32, alpha float32) {
	cred, _ := (C.GLclampf)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLclampf)(green), cgoAllocsUnknown
	cblue, _ := (C.GLclampf)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLclampf)(alpha), cgoAllocsUnknown
	C.glClearColor(cred, cgreen, cblue, calpha)
}

// ClearDepthf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearDepthf.xml
func ClearDepthf(depth float32) {
	cdepth, _ := (C.GLclampf)(depth), cgoAllocsUnknown
	C.glClearDepthf(cdepth)
}

// ClipPlanef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClipPlanef.xml
func ClipPlanef(plane uint32, equation []float32) {
	cplane, _ := (C.GLenum)(plane), cgoAllocsUnknown
	cequation, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&equation)).Data)), cgoAllocsUnknown
	C.glClipPlanef(cplane, cequation)
}

// Color4f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColor4f.xml
func Color4f(red float32, green float32, blue float32, alpha float32) {
	cred, _ := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, _ := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glColor4f(cred, cgreen, cblue, calpha)
}

// DepthRangef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthRangef.xml
func DepthRangef(zNear float32, zFar float32) {
	czNear, _ := (C.GLclampf)(zNear), cgoAllocsUnknown
	czFar, _ := (C.GLclampf)(zFar), cgoAllocsUnknown
	C.glDepthRangef(czNear, czFar)
}

// Fogf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFogf.xml
func Fogf(pname uint32, param float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glFogf(cpname, cparam)
}

// Fogfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFogfv.xml
func Fogfv(pname uint32, params []float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glFogfv(cpname, cparams)
}

// Frustumf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFrustumf.xml
func Frustumf(left float32, right float32, bottom float32, top float32, zNear float32, zFar float32) {
	cleft, _ := (C.GLfloat)(left), cgoAllocsUnknown
	cright, _ := (C.GLfloat)(right), cgoAllocsUnknown
	cbottom, _ := (C.GLfloat)(bottom), cgoAllocsUnknown
	ctop, _ := (C.GLfloat)(top), cgoAllocsUnknown
	czNear, _ := (C.GLfloat)(zNear), cgoAllocsUnknown
	czFar, _ := (C.GLfloat)(zFar), cgoAllocsUnknown
	C.glFrustumf(cleft, cright, cbottom, ctop, czNear, czFar)
}

// GetClipPlanef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetClipPlanef.xml
func GetClipPlanef(pname uint32, eqn *[4]float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	ceqn, _ := *(**C.GLfloat)(unsafe.Pointer(&eqn)), cgoAllocsUnknown
	C.glGetClipPlanef(cpname, ceqn)
}

// GetFloatv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFloatv.xml
func GetFloatv(pname uint32, params []float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetFloatv(cpname, cparams)
}

// GetLightfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetLightfv.xml
func GetLightfv(light uint32, pname uint32, params []float32) {
	clight, _ := (C.GLenum)(light), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetLightfv(clight, cpname, cparams)
}

// GetMaterialfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetMaterialfv.xml
func GetMaterialfv(face uint32, pname uint32, params []float32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetMaterialfv(cface, cpname, cparams)
}

// GetTexEnvfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexEnvfv.xml
func GetTexEnvfv(env uint32, pname uint32, params []float32) {
	cenv, _ := (C.GLenum)(env), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexEnvfv(cenv, cpname, cparams)
}

// GetTexParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameterfv.xml
func GetTexParameterfv(target uint32, pname uint32, params []float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameterfv(ctarget, cpname, cparams)
}

// LightModelf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightModelf.xml
func LightModelf(pname uint32, param float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glLightModelf(cpname, cparam)
}

// LightModelfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightModelfv.xml
func LightModelfv(pname uint32, params []float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightModelfv(cpname, cparams)
}

// Lightf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightf.xml
func Lightf(light uint32, pname uint32, param float32) {
	clight, _ := (C.GLenum)(light), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glLightf(clight, cpname, cparam)
}

// Lightfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightfv.xml
func Lightfv(light uint32, pname uint32, params []float32) {
	clight, _ := (C.GLenum)(light), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightfv(clight, cpname, cparams)
}

// SetLineWidth function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLineWidth.xml
func SetLineWidth(width float32) {
	cwidth, _ := (C.GLfloat)(width), cgoAllocsUnknown
	C.glLineWidth(cwidth)
}

// LoadMatrixf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLoadMatrixf.xml
func LoadMatrixf(m []float32) {
	cm, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glLoadMatrixf(cm)
}

// Materialf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMaterialf.xml
func Materialf(face uint32, pname uint32, param float32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glMaterialf(cface, cpname, cparam)
}

// Materialfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMaterialfv.xml
func Materialfv(face uint32, pname uint32, params []float32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glMaterialfv(cface, cpname, cparams)
}

// MultMatrixf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMultMatrixf.xml
func MultMatrixf(m []float32) {
	cm, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glMultMatrixf(cm)
}

// MultiTexCoord4f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMultiTexCoord4f.xml
func MultiTexCoord4f(target uint32, s float32, t float32, r float32, q float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cs, _ := (C.GLfloat)(s), cgoAllocsUnknown
	ct, _ := (C.GLfloat)(t), cgoAllocsUnknown
	cr, _ := (C.GLfloat)(r), cgoAllocsUnknown
	cq, _ := (C.GLfloat)(q), cgoAllocsUnknown
	C.glMultiTexCoord4f(ctarget, cs, ct, cr, cq)
}

// Normal3f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glNormal3f.xml
func Normal3f(nx float32, ny float32, nz float32) {
	cnx, _ := (C.GLfloat)(nx), cgoAllocsUnknown
	cny, _ := (C.GLfloat)(ny), cgoAllocsUnknown
	cnz, _ := (C.GLfloat)(nz), cgoAllocsUnknown
	C.glNormal3f(cnx, cny, cnz)
}

// Orthof function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glOrthof.xml
func Orthof(left float32, right float32, bottom float32, top float32, zNear float32, zFar float32) {
	cleft, _ := (C.GLfloat)(left), cgoAllocsUnknown
	cright, _ := (C.GLfloat)(right), cgoAllocsUnknown
	cbottom, _ := (C.GLfloat)(bottom), cgoAllocsUnknown
	ctop, _ := (C.GLfloat)(top), cgoAllocsUnknown
	czNear, _ := (C.GLfloat)(zNear), cgoAllocsUnknown
	czFar, _ := (C.GLfloat)(zFar), cgoAllocsUnknown
	C.glOrthof(cleft, cright, cbottom, ctop, czNear, czFar)
}

// PointParameterf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointParameterf.xml
func PointParameterf(pname uint32, param float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glPointParameterf(cpname, cparam)
}

// PointParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointParameterfv.xml
func PointParameterfv(pname uint32, params []float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glPointParameterfv(cpname, cparams)
}

// SetPointSize function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointSize.xml
func SetPointSize(size float32) {
	csize, _ := (C.GLfloat)(size), cgoAllocsUnknown
	C.glPointSize(csize)
}

// PolygonOffset function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPolygonOffset.xml
func PolygonOffset(factor float32, units float32) {
	cfactor, _ := (C.GLfloat)(factor), cgoAllocsUnknown
	cunits, _ := (C.GLfloat)(units), cgoAllocsUnknown
	C.glPolygonOffset(cfactor, cunits)
}

// Rotatef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glRotatef.xml
func Rotatef(angle float32, x float32, y float32, z float32) {
	cangle, _ := (C.GLfloat)(angle), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	C.glRotatef(cangle, cx, cy, cz)
}

// Scalef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glScalef.xml
func Scalef(x float32, y float32, z float32) {
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	C.glScalef(cx, cy, cz)
}

// TexEnvf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexEnvf.xml
func TexEnvf(target uint32, pname uint32, param float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glTexEnvf(ctarget, cpname, cparam)
}

// TexEnvfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexEnvfv.xml
func TexEnvfv(target uint32, pname uint32, params []float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexEnvfv(ctarget, cpname, cparams)
}

// TexParameterf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterf.xml
func TexParameterf(target uint32, pname uint32, param float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glTexParameterf(ctarget, cpname, cparam)
}

// TexParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterfv.xml
func TexParameterfv(target uint32, pname uint32, params []float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameterfv(ctarget, cpname, cparams)
}

// Translatef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTranslatef.xml
func Translatef(x float32, y float32, z float32) {
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	C.glTranslatef(cx, cy, cz)
}

// SetActiveTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glActiveTexture.xml
func SetActiveTexture(texture uint32) {
	ctexture, _ := (C.GLenum)(texture), cgoAllocsUnknown
	C.glActiveTexture(ctexture)
}

// AlphaFuncx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glAlphaFuncx.xml
func AlphaFuncx(_func uint32, ref int32) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLclampx)(ref), cgoAllocsUnknown
	C.glAlphaFuncx(c_func, cref)
}

// BindBuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindBuffer.xml
func BindBuffer(target uint32, buffer uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cbuffer, _ := (C.GLuint)(buffer), cgoAllocsUnknown
	C.glBindBuffer(ctarget, cbuffer)
}

// BindTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindTexture.xml
func BindTexture(target uint32, texture uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	C.glBindTexture(ctarget, ctexture)
}

// BlendFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendFunc.xml
func BlendFunc(sfactor uint32, dfactor uint32) {
	csfactor, _ := (C.GLenum)(sfactor), cgoAllocsUnknown
	cdfactor, _ := (C.GLenum)(dfactor), cgoAllocsUnknown
	C.glBlendFunc(csfactor, cdfactor)
}

// BufferData function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBufferData.xml
func BufferData(target uint32, size int, data unsafe.Pointer, usage uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	csize, _ := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	cusage, _ := (C.GLenum)(usage), cgoAllocsUnknown
	C.glBufferData(ctarget, csize, cdata, cusage)
}

// BufferSubData function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBufferSubData.xml
func BufferSubData(target uint32, offset int, size int, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	coffset, _ := (C.GLintptr)(offset), cgoAllocsUnknown
	csize, _ := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	C.glBufferSubData(ctarget, coffset, csize, cdata)
}

// ClearFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClear.xml
func ClearFunc(mask uint32) {
	cmask, _ := (C.GLbitfield)(mask), cgoAllocsUnknown
	C.glClear(cmask)
}

// ClearColorx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearColorx.xml
func ClearColorx(red int32, green int32, blue int32, alpha int32) {
	cred, _ := (C.GLclampx)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLclampx)(green), cgoAllocsUnknown
	cblue, _ := (C.GLclampx)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLclampx)(alpha), cgoAllocsUnknown
	C.glClearColorx(cred, cgreen, cblue, calpha)
}

// ClearDepthx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearDepthx.xml
func ClearDepthx(depth int32) {
	cdepth, _ := (C.GLclampx)(depth), cgoAllocsUnknown
	C.glClearDepthx(cdepth)
}

// ClearStencil function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearStencil.xml
func ClearStencil(s int32) {
	cs, _ := (C.GLint)(s), cgoAllocsUnknown
	C.glClearStencil(cs)
}

// ClientSetActiveTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClientActiveTexture.xml
func ClientSetActiveTexture(texture uint32) {
	ctexture, _ := (C.GLenum)(texture), cgoAllocsUnknown
	C.glClientActiveTexture(ctexture)
}

// ClipPlanex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClipPlanex.xml
func ClipPlanex(plane uint32, equation []int32) {
	cplane, _ := (C.GLenum)(plane), cgoAllocsUnknown
	cequation, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&equation)).Data)), cgoAllocsUnknown
	C.glClipPlanex(cplane, cequation)
}

// Color4ub function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColor4ub.xml
func Color4ub(red byte, green byte, blue byte, alpha byte) {
	cred, _ := (C.GLubyte)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLubyte)(green), cgoAllocsUnknown
	cblue, _ := (C.GLubyte)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLubyte)(alpha), cgoAllocsUnknown
	C.glColor4ub(cred, cgreen, cblue, calpha)
}

// Color4x function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColor4x.xml
func Color4x(red int32, green int32, blue int32, alpha int32) {
	cred, _ := (C.GLfixed)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLfixed)(green), cgoAllocsUnknown
	cblue, _ := (C.GLfixed)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLfixed)(alpha), cgoAllocsUnknown
	C.glColor4x(cred, cgreen, cblue, calpha)
}

// ColorMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColorMask.xml
func ColorMask(red byte, green byte, blue byte, alpha byte) {
	cred, _ := (C.GLboolean)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLboolean)(green), cgoAllocsUnknown
	cblue, _ := (C.GLboolean)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLboolean)(alpha), cgoAllocsUnknown
	C.glColorMask(cred, cgreen, cblue, calpha)
}

// ColorPointer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColorPointer.xml
func ColorPointer(size int32, kind uint32, stride int32, pointer unsafe.Pointer) {
	csize, _ := (C.GLint)(size), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := (unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glColorPointer(csize, ckind, cstride, cpointer)
}

// CompressedTexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompressedTexImage2D.xml
func CompressedTexImage2D(target uint32, level int32, internalformat uint32, width int32, height int32, border int32, imageSize int32, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	cimageSize, _ := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	C.glCompressedTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cimageSize, cdata)
}

// CompressedTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompressedTexSubImage2D.xml
func CompressedTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, imageSize int32, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	cimageSize, _ := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	C.glCompressedTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, cimageSize, cdata)
}

// CopyTexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCopyTexImage2D.xml
func CopyTexImage2D(target uint32, level int32, internalformat uint32, x int32, y int32, width int32, height int32, border int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	C.glCopyTexImage2D(ctarget, clevel, cinternalformat, cx, cy, cwidth, cheight, cborder)
}

// CopyTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCopyTexSubImage2D.xml
func CopyTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, x int32, y int32, width int32, height int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glCopyTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cx, cy, cwidth, cheight)
}

// SetCullFace function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCullFace.xml
func SetCullFace(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glCullFace(cmode)
}

// DeleteBuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteBuffers.xml
func DeleteBuffers(n int32, buffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glDeleteBuffers(cn, cbuffers)
}

// DeleteTextures function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteTextures.xml
func DeleteTextures(n int32, textures []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glDeleteTextures(cn, ctextures)
}

// SetDepthFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthFunc.xml
func SetDepthFunc(_func uint32) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	C.glDepthFunc(c_func)
}

// DepthMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthMask.xml
func DepthMask(flag byte) {
	cflag, _ := (C.GLboolean)(flag), cgoAllocsUnknown
	C.glDepthMask(cflag)
}

// DepthRangex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthRangex.xml
func DepthRangex(zNear int32, zFar int32) {
	czNear, _ := (C.GLclampx)(zNear), cgoAllocsUnknown
	czFar, _ := (C.GLclampx)(zFar), cgoAllocsUnknown
	C.glDepthRangex(czNear, czFar)
}

// Disable function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDisable.xml
func Disable(cap uint32) {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	C.glDisable(ccap)
}

// DisableClientState function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDisableClientState.xml
func DisableClientState(array uint32) {
	carray, _ := (C.GLenum)(array), cgoAllocsUnknown
	C.glDisableClientState(carray)
}

// DrawArrays function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDrawArrays.xml
func DrawArrays(mode uint32, first int32, count int32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	cfirst, _ := (C.GLint)(first), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	C.glDrawArrays(cmode, cfirst, ccount)
}

// DrawElements function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDrawElements.xml
func DrawElements(mode uint32, count int32, kind uint32, indices unsafe.Pointer) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cindices, _ := (unsafe.Pointer)(unsafe.Pointer(indices)), cgoAllocsUnknown
	C.glDrawElements(cmode, ccount, ckind, cindices)
}

// Enable function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnable.xml
func Enable(cap uint32) {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	C.glEnable(ccap)
}

// EnableClientState function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnableClientState.xml
func EnableClientState(array uint32) {
	carray, _ := (C.GLenum)(array), cgoAllocsUnknown
	C.glEnableClientState(carray)
}

// Finish function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFinish.xml
func Finish() {
	C.glFinish()
}

// Flush function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFlush.xml
func Flush() {
	C.glFlush()
}

// Fogx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFogx.xml
func Fogx(pname uint32, param int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glFogx(cpname, cparam)
}

// Fogxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFogxv.xml
func Fogxv(pname uint32, params []int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glFogxv(cpname, cparams)
}

// SetFrontFace function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFrontFace.xml
func SetFrontFace(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glFrontFace(cmode)
}

// Frustumx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFrustumx.xml
func Frustumx(left int32, right int32, bottom int32, top int32, zNear int32, zFar int32) {
	cleft, _ := (C.GLfixed)(left), cgoAllocsUnknown
	cright, _ := (C.GLfixed)(right), cgoAllocsUnknown
	cbottom, _ := (C.GLfixed)(bottom), cgoAllocsUnknown
	ctop, _ := (C.GLfixed)(top), cgoAllocsUnknown
	czNear, _ := (C.GLfixed)(zNear), cgoAllocsUnknown
	czFar, _ := (C.GLfixed)(zFar), cgoAllocsUnknown
	C.glFrustumx(cleft, cright, cbottom, ctop, czNear, czFar)
}

// GetBooleanv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetBooleanv.xml
func GetBooleanv(pname uint32, params []byte) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLboolean)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetBooleanv(cpname, cparams)
}

// GetBufferParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetBufferParameteriv.xml
func GetBufferParameteriv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetBufferParameteriv(ctarget, cpname, cparams)
}

// GetClipPlanex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetClipPlanex.xml
func GetClipPlanex(pname uint32, eqn *[4]int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	ceqn, _ := *(**C.GLfixed)(unsafe.Pointer(&eqn)), cgoAllocsUnknown
	C.glGetClipPlanex(cpname, ceqn)
}

// GenBuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenBuffers.xml
func GenBuffers(n int32, buffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glGenBuffers(cn, cbuffers)
}

// GenTextures function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenTextures.xml
func GenTextures(n int32, textures []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glGenTextures(cn, ctextures)
}

// GetError function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetError.xml
func GetError() uint32 {
	__ret := C.glGetError()
	__v := (uint32)(__ret)
	return __v
}

// GetFixedv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFixedv.xml
func GetFixedv(pname uint32, params []int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetFixedv(cpname, cparams)
}

// GetIntegerv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetIntegerv.xml
func GetIntegerv(pname uint32, params []int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetIntegerv(cpname, cparams)
}

// GetLightxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetLightxv.xml
func GetLightxv(light uint32, pname uint32, params []int32) {
	clight, _ := (C.GLenum)(light), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetLightxv(clight, cpname, cparams)
}

// GetMaterialxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetMaterialxv.xml
func GetMaterialxv(face uint32, pname uint32, params []int32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetMaterialxv(cface, cpname, cparams)
}

// GetPointerv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetPointerv.xml
func GetPointerv(pname uint32, params []unsafe.Pointer) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetPointerv(cpname, cparams)
}

// GetString function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetString.xml
func GetString(name uint32) string {
	cname, _ := (C.GLenum)(name), cgoAllocsUnknown
	__ret := C.glGetString(cname)
	__v := packPUbyteString(__ret)
	return __v
}

// GetTexEnviv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexEnviv.xml
func GetTexEnviv(env uint32, pname uint32, params []int32) {
	cenv, _ := (C.GLenum)(env), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexEnviv(cenv, cpname, cparams)
}

// GetTexEnvxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexEnvxv.xml
func GetTexEnvxv(env uint32, pname uint32, params []int32) {
	cenv, _ := (C.GLenum)(env), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexEnvxv(cenv, cpname, cparams)
}

// GetTexParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameteriv.xml
func GetTexParameteriv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameteriv(ctarget, cpname, cparams)
}

// GetTexParameterxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameterxv.xml
func GetTexParameterxv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameterxv(ctarget, cpname, cparams)
}

// Hint function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glHint.xml
func Hint(target uint32, mode uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glHint(ctarget, cmode)
}

// IsBuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsBuffer.xml
func IsBuffer(buffer uint32) byte {
	cbuffer, _ := (C.GLuint)(buffer), cgoAllocsUnknown
	__ret := C.glIsBuffer(cbuffer)
	__v := (byte)(__ret)
	return __v
}

// IsEnabled function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsEnabled.xml
func IsEnabled(cap uint32) byte {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	__ret := C.glIsEnabled(ccap)
	__v := (byte)(__ret)
	return __v
}

// IsTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsTexture.xml
func IsTexture(texture uint32) byte {
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	__ret := C.glIsTexture(ctexture)
	__v := (byte)(__ret)
	return __v
}

// LightModelx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightModelx.xml
func LightModelx(pname uint32, param int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glLightModelx(cpname, cparam)
}

// LightModelxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightModelxv.xml
func LightModelxv(pname uint32, params []int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightModelxv(cpname, cparams)
}

// Lightx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightx.xml
func Lightx(light uint32, pname uint32, param int32) {
	clight, _ := (C.GLenum)(light), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glLightx(clight, cpname, cparam)
}

// Lightxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLightxv.xml
func Lightxv(light uint32, pname uint32, params []int32) {
	clight, _ := (C.GLenum)(light), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightxv(clight, cpname, cparams)
}

// LineWidthx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLineWidthx.xml
func LineWidthx(width int32) {
	cwidth, _ := (C.GLfixed)(width), cgoAllocsUnknown
	C.glLineWidthx(cwidth)
}

// LoadIdentity function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLoadIdentity.xml
func LoadIdentity() {
	C.glLoadIdentity()
}

// LoadMatrixx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLoadMatrixx.xml
func LoadMatrixx(m []int32) {
	cm, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glLoadMatrixx(cm)
}

// LogicOp function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLogicOp.xml
func LogicOp(opcode uint32) {
	copcode, _ := (C.GLenum)(opcode), cgoAllocsUnknown
	C.glLogicOp(copcode)
}

// Materialx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMaterialx.xml
func Materialx(face uint32, pname uint32, param int32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glMaterialx(cface, cpname, cparam)
}

// Materialxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMaterialxv.xml
func Materialxv(face uint32, pname uint32, params []int32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glMaterialxv(cface, cpname, cparams)
}

// SetMatrixMode function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMatrixMode.xml
func SetMatrixMode(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glMatrixMode(cmode)
}

// MultMatrixx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMultMatrixx.xml
func MultMatrixx(m []int32) {
	cm, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glMultMatrixx(cm)
}

// MultiTexCoord4x function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glMultiTexCoord4x.xml
func MultiTexCoord4x(target uint32, s int32, t int32, r int32, q int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cs, _ := (C.GLfixed)(s), cgoAllocsUnknown
	ct, _ := (C.GLfixed)(t), cgoAllocsUnknown
	cr, _ := (C.GLfixed)(r), cgoAllocsUnknown
	cq, _ := (C.GLfixed)(q), cgoAllocsUnknown
	C.glMultiTexCoord4x(ctarget, cs, ct, cr, cq)
}

// Normal3x function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glNormal3x.xml
func Normal3x(nx int32, ny int32, nz int32) {
	cnx, _ := (C.GLfixed)(nx), cgoAllocsUnknown
	cny, _ := (C.GLfixed)(ny), cgoAllocsUnknown
	cnz, _ := (C.GLfixed)(nz), cgoAllocsUnknown
	C.glNormal3x(cnx, cny, cnz)
}

// NormalPointer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glNormalPointer.xml
func NormalPointer(kind uint32, stride int32, pointer unsafe.Pointer) {
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := (unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glNormalPointer(ckind, cstride, cpointer)
}

// Orthox function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glOrthox.xml
func Orthox(left int32, right int32, bottom int32, top int32, zNear int32, zFar int32) {
	cleft, _ := (C.GLfixed)(left), cgoAllocsUnknown
	cright, _ := (C.GLfixed)(right), cgoAllocsUnknown
	cbottom, _ := (C.GLfixed)(bottom), cgoAllocsUnknown
	ctop, _ := (C.GLfixed)(top), cgoAllocsUnknown
	czNear, _ := (C.GLfixed)(zNear), cgoAllocsUnknown
	czFar, _ := (C.GLfixed)(zFar), cgoAllocsUnknown
	C.glOrthox(cleft, cright, cbottom, ctop, czNear, czFar)
}

// PixelStorei function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPixelStorei.xml
func PixelStorei(pname uint32, param int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glPixelStorei(cpname, cparam)
}

// PointParameterx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointParameterx.xml
func PointParameterx(pname uint32, param int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glPointParameterx(cpname, cparam)
}

// PointParameterxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointParameterxv.xml
func PointParameterxv(pname uint32, params []int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glPointParameterxv(cpname, cparams)
}

// PointSizex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointSizex.xml
func PointSizex(size int32) {
	csize, _ := (C.GLfixed)(size), cgoAllocsUnknown
	C.glPointSizex(csize)
}

// PolygonOffsetx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPolygonOffsetx.xml
func PolygonOffsetx(factor int32, units int32) {
	cfactor, _ := (C.GLfixed)(factor), cgoAllocsUnknown
	cunits, _ := (C.GLfixed)(units), cgoAllocsUnknown
	C.glPolygonOffsetx(cfactor, cunits)
}

// PopMatrix function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPopMatrix.xml
func PopMatrix() {
	C.glPopMatrix()
}

// PushMatrix function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPushMatrix.xml
func PushMatrix() {
	C.glPushMatrix()
}

// ReadPixels function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glReadPixels.xml
func ReadPixels(x int32, y int32, width int32, height int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := (unsafe.Pointer)(unsafe.Pointer(pixels)), cgoAllocsUnknown
	C.glReadPixels(cx, cy, cwidth, cheight, cformat, ckind, cpixels)
}

// Rotatex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glRotatex.xml
func Rotatex(angle int32, x int32, y int32, z int32) {
	cangle, _ := (C.GLfixed)(angle), cgoAllocsUnknown
	cx, _ := (C.GLfixed)(x), cgoAllocsUnknown
	cy, _ := (C.GLfixed)(y), cgoAllocsUnknown
	cz, _ := (C.GLfixed)(z), cgoAllocsUnknown
	C.glRotatex(cangle, cx, cy, cz)
}

// SetSampleCoverage function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glSampleCoverage.xml
func SetSampleCoverage(value float32, invert byte) {
	cvalue, _ := (C.GLclampf)(value), cgoAllocsUnknown
	cinvert, _ := (C.GLboolean)(invert), cgoAllocsUnknown
	C.glSampleCoverage(cvalue, cinvert)
}

// SampleCoveragex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glSampleCoveragex.xml
func SampleCoveragex(value int32, invert byte) {
	cvalue, _ := (C.GLclampx)(value), cgoAllocsUnknown
	cinvert, _ := (C.GLboolean)(invert), cgoAllocsUnknown
	C.glSampleCoveragex(cvalue, cinvert)
}

// Scalex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glScalex.xml
func Scalex(x int32, y int32, z int32) {
	cx, _ := (C.GLfixed)(x), cgoAllocsUnknown
	cy, _ := (C.GLfixed)(y), cgoAllocsUnknown
	cz, _ := (C.GLfixed)(z), cgoAllocsUnknown
	C.glScalex(cx, cy, cz)
}

// Scissor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glScissor.xml
func Scissor(x int32, y int32, width int32, height int32) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glScissor(cx, cy, cwidth, cheight)
}

// SetShadeModel function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glShadeModel.xml
func SetShadeModel(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glShadeModel(cmode)
}

// SetStencilFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilFunc.xml
func SetStencilFunc(_func uint32, ref int32, mask uint32) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLint)(ref), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilFunc(c_func, cref, cmask)
}

// StencilMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilMask.xml
func StencilMask(mask uint32) {
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilMask(cmask)
}

// StencilOp function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilOp.xml
func StencilOp(fail uint32, zfail uint32, zpass uint32) {
	cfail, _ := (C.GLenum)(fail), cgoAllocsUnknown
	czfail, _ := (C.GLenum)(zfail), cgoAllocsUnknown
	czpass, _ := (C.GLenum)(zpass), cgoAllocsUnknown
	C.glStencilOp(cfail, czfail, czpass)
}

// TexCoordPointer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexCoordPointer.xml
func TexCoordPointer(size int32, kind uint32, stride int32, pointer unsafe.Pointer) {
	csize, _ := (C.GLint)(size), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := (unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glTexCoordPointer(csize, ckind, cstride, cpointer)
}

// TexEnvi function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexEnvi.xml
func TexEnvi(target uint32, pname uint32, param int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glTexEnvi(ctarget, cpname, cparam)
}

// TexEnvx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexEnvx.xml
func TexEnvx(target uint32, pname uint32, param int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glTexEnvx(ctarget, cpname, cparam)
}

// TexEnviv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexEnviv.xml
func TexEnviv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexEnviv(ctarget, cpname, cparams)
}

// TexEnvxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexEnvxv.xml
func TexEnvxv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexEnvxv(ctarget, cpname, cparams)
}

// TexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexImage2D.xml
func TexImage2D(target uint32, level int32, internalformat int32, width int32, height int32, border int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLint)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := (unsafe.Pointer)(unsafe.Pointer(pixels)), cgoAllocsUnknown
	C.glTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cformat, ckind, cpixels)
}

// TexParameteri function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameteri.xml
func TexParameteri(target uint32, pname uint32, param int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glTexParameteri(ctarget, cpname, cparam)
}

// TexParameterx function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterx.xml
func TexParameterx(target uint32, pname uint32, param int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfixed)(param), cgoAllocsUnknown
	C.glTexParameterx(ctarget, cpname, cparam)
}

// TexParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameteriv.xml
func TexParameteriv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameteriv(ctarget, cpname, cparams)
}

// TexParameterxv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterxv.xml
func TexParameterxv(target uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameterxv(ctarget, cpname, cparams)
}

// TexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexSubImage2D.xml
func TexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := (unsafe.Pointer)(unsafe.Pointer(pixels)), cgoAllocsUnknown
	C.glTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, ckind, cpixels)
}

// Translatex function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTranslatex.xml
func Translatex(x int32, y int32, z int32) {
	cx, _ := (C.GLfixed)(x), cgoAllocsUnknown
	cy, _ := (C.GLfixed)(y), cgoAllocsUnknown
	cz, _ := (C.GLfixed)(z), cgoAllocsUnknown
	C.glTranslatex(cx, cy, cz)
}

// VertexPointer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexPointer.xml
func VertexPointer(size int32, kind uint32, stride int32, pointer unsafe.Pointer) {
	csize, _ := (C.GLint)(size), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := (unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glVertexPointer(csize, ckind, cstride, cpointer)
}

// SetViewport function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glViewport.xml
func SetViewport(x int32, y int32, width int32, height int32) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glViewport(cx, cy, cwidth, cheight)
}

// PointSizePointerOES function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPointSizePointerOES.xml
func PointSizePointerOES(kind uint32, stride int32, pointer unsafe.Pointer) {
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := (unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glPointSizePointerOES(ckind, cstride, cpointer)
}
