// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Jan 2017 23:48:37 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include <EGL/egl.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

