// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 05 Nov 2016 19:40:02 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include <EGL/egl.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

