// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 04 Jul 2017 10:30:14 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package egl provides Go bindings for EGL API.
*/
package egl
