// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Jan 2017 22:41:08 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include <GLES2/gl2.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

