// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 02 Sep 2016 16:37:58 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include <GLES2/gl2.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

