// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 26 Feb 2017 06:20:45 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package gles2 provides Go bindings for the OpenGL ES v2 API.
*/
package gles2
