// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:50:45 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

package gles2

/*
#cgo LDFLAGS: -lGLESv2
#include <GLES2/gl2.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// ActiveTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glActiveTexture.xml
func ActiveTexture(texture uint32) {
	ctexture, _ := (C.GLenum)(texture), cgoAllocsUnknown
	C.glActiveTexture(ctexture)
}

// AttachShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glAttachShader.xml
func AttachShader(program uint32, shader uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glAttachShader(cprogram, cshader)
}

// BindAttribLocation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindAttribLocation.xml
func BindAttribLocation(program uint32, index uint32, name string) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	C.glBindAttribLocation(cprogram, cindex, cname)
}

// BindBuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindBuffer.xml
func BindBuffer(target uint32, buffer uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cbuffer, _ := (C.GLuint)(buffer), cgoAllocsUnknown
	C.glBindBuffer(ctarget, cbuffer)
}

// BindFramebuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindFramebuffer.xml
func BindFramebuffer(target uint32, framebuffer uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cframebuffer, _ := (C.GLuint)(framebuffer), cgoAllocsUnknown
	C.glBindFramebuffer(ctarget, cframebuffer)
}

// BindRenderbuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindRenderbuffer.xml
func BindRenderbuffer(target uint32, renderbuffer uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	crenderbuffer, _ := (C.GLuint)(renderbuffer), cgoAllocsUnknown
	C.glBindRenderbuffer(ctarget, crenderbuffer)
}

// BindTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindTexture.xml
func BindTexture(target uint32, texture uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	C.glBindTexture(ctarget, ctexture)
}

// BlendColor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendColor.xml
func BlendColor(red float32, green float32, blue float32, alpha float32) {
	cred, _ := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, _ := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glBlendColor(cred, cgreen, cblue, calpha)
}

// BlendEquation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendEquation.xml
func BlendEquation(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glBlendEquation(cmode)
}

// BlendEquationSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendEquationSeparate.xml
func BlendEquationSeparate(modeRGB uint32, modeAlpha uint32) {
	cmodeRGB, _ := (C.GLenum)(modeRGB), cgoAllocsUnknown
	cmodeAlpha, _ := (C.GLenum)(modeAlpha), cgoAllocsUnknown
	C.glBlendEquationSeparate(cmodeRGB, cmodeAlpha)
}

// BlendFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendFunc.xml
func BlendFunc(sfactor uint32, dfactor uint32) {
	csfactor, _ := (C.GLenum)(sfactor), cgoAllocsUnknown
	cdfactor, _ := (C.GLenum)(dfactor), cgoAllocsUnknown
	C.glBlendFunc(csfactor, cdfactor)
}

// BlendFuncSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendFuncSeparate.xml
func BlendFuncSeparate(sfactorRGB uint32, dfactorRGB uint32, sfactorAlpha uint32, dfactorAlpha uint32) {
	csfactorRGB, _ := (C.GLenum)(sfactorRGB), cgoAllocsUnknown
	cdfactorRGB, _ := (C.GLenum)(dfactorRGB), cgoAllocsUnknown
	csfactorAlpha, _ := (C.GLenum)(sfactorAlpha), cgoAllocsUnknown
	cdfactorAlpha, _ := (C.GLenum)(dfactorAlpha), cgoAllocsUnknown
	C.glBlendFuncSeparate(csfactorRGB, cdfactorRGB, csfactorAlpha, cdfactorAlpha)
}

// BufferData function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBufferData.xml
func BufferData(target uint32, size int, data unsafe.Pointer, usage uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	csize, _ := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, _ := data, cgoAllocsUnknown
	cusage, _ := (C.GLenum)(usage), cgoAllocsUnknown
	C.glBufferData(ctarget, csize, cdata, cusage)
}

// BufferSubData function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBufferSubData.xml
func BufferSubData(target uint32, offset int, size int, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	coffset, _ := (C.GLintptr)(offset), cgoAllocsUnknown
	csize, _ := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, _ := data, cgoAllocsUnknown
	C.glBufferSubData(ctarget, coffset, csize, cdata)
}

// CheckFramebufferStatus function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCheckFramebufferStatus.xml
func CheckFramebufferStatus(target uint32) uint32 {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	__ret := C.glCheckFramebufferStatus(ctarget)
	__v := (uint32)(__ret)
	return __v
}

// Clear function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClear.xml
func Clear(mask uint32) {
	cmask, _ := (C.GLbitfield)(mask), cgoAllocsUnknown
	C.glClear(cmask)
}

// ClearColor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearColor.xml
func ClearColor(red float32, green float32, blue float32, alpha float32) {
	cred, _ := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, _ := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glClearColor(cred, cgreen, cblue, calpha)
}

// ClearDepthf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearDepthf.xml
func ClearDepthf(d float32) {
	cd, _ := (C.GLfloat)(d), cgoAllocsUnknown
	C.glClearDepthf(cd)
}

// ClearStencil function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearStencil.xml
func ClearStencil(s int32) {
	cs, _ := (C.GLint)(s), cgoAllocsUnknown
	C.glClearStencil(cs)
}

// ColorMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColorMask.xml
func ColorMask(red byte, green byte, blue byte, alpha byte) {
	cred, _ := (C.GLboolean)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLboolean)(green), cgoAllocsUnknown
	cblue, _ := (C.GLboolean)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLboolean)(alpha), cgoAllocsUnknown
	C.glColorMask(cred, cgreen, cblue, calpha)
}

// CompileShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompileShader.xml
func CompileShader(shader uint32) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glCompileShader(cshader)
}

// CompressedTexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompressedTexImage2D.xml
func CompressedTexImage2D(target uint32, level int32, internalformat uint32, width int32, height int32, border int32, imageSize int32, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	cimageSize, _ := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, _ := data, cgoAllocsUnknown
	C.glCompressedTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cimageSize, cdata)
}

// CompressedTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompressedTexSubImage2D.xml
func CompressedTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, imageSize int32, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	cimageSize, _ := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, _ := data, cgoAllocsUnknown
	C.glCompressedTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, cimageSize, cdata)
}

// CopyTexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCopyTexImage2D.xml
func CopyTexImage2D(target uint32, level int32, internalformat uint32, x int32, y int32, width int32, height int32, border int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	C.glCopyTexImage2D(ctarget, clevel, cinternalformat, cx, cy, cwidth, cheight, cborder)
}

// CopyTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCopyTexSubImage2D.xml
func CopyTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, x int32, y int32, width int32, height int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glCopyTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cx, cy, cwidth, cheight)
}

// CreateProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCreateProgram.xml
func CreateProgram() uint32 {
	__ret := C.glCreateProgram()
	__v := (uint32)(__ret)
	return __v
}

// CreateShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCreateShader.xml
func CreateShader(kind uint32) uint32 {
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	__ret := C.glCreateShader(ckind)
	__v := (uint32)(__ret)
	return __v
}

// CullFace function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCullFace.xml
func CullFace(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glCullFace(cmode)
}

// DeleteBuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteBuffers.xml
func DeleteBuffers(n int32, buffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glDeleteBuffers(cn, cbuffers)
}

// DeleteFramebuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteFramebuffers.xml
func DeleteFramebuffers(n int32, framebuffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cframebuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&framebuffers)).Data)), cgoAllocsUnknown
	C.glDeleteFramebuffers(cn, cframebuffers)
}

// DeleteProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteProgram.xml
func DeleteProgram(program uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glDeleteProgram(cprogram)
}

// DeleteRenderbuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteRenderbuffers.xml
func DeleteRenderbuffers(n int32, renderbuffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	crenderbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&renderbuffers)).Data)), cgoAllocsUnknown
	C.glDeleteRenderbuffers(cn, crenderbuffers)
}

// DeleteShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteShader.xml
func DeleteShader(shader uint32) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glDeleteShader(cshader)
}

// DeleteTextures function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteTextures.xml
func DeleteTextures(n int32, textures []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glDeleteTextures(cn, ctextures)
}

// DepthFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthFunc.xml
func DepthFunc(_func uint32) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	C.glDepthFunc(c_func)
}

// DepthMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthMask.xml
func DepthMask(flag byte) {
	cflag, _ := (C.GLboolean)(flag), cgoAllocsUnknown
	C.glDepthMask(cflag)
}

// DepthRangef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthRangef.xml
func DepthRangef(n float32, f float32) {
	cn, _ := (C.GLfloat)(n), cgoAllocsUnknown
	cf, _ := (C.GLfloat)(f), cgoAllocsUnknown
	C.glDepthRangef(cn, cf)
}

// DetachShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDetachShader.xml
func DetachShader(program uint32, shader uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glDetachShader(cprogram, cshader)
}

// Disable function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDisable.xml
func Disable(cap uint32) {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	C.glDisable(ccap)
}

// DisableVertexAttribArray function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDisableVertexAttribArray.xml
func DisableVertexAttribArray(index uint32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	C.glDisableVertexAttribArray(cindex)
}

// DrawArrays function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDrawArrays.xml
func DrawArrays(mode uint32, first int32, count int32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	cfirst, _ := (C.GLint)(first), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	C.glDrawArrays(cmode, cfirst, ccount)
}

// DrawElements function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDrawElements.xml
func DrawElements(mode uint32, count int32, kind uint32, indices unsafe.Pointer) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cindices, _ := indices, cgoAllocsUnknown
	C.glDrawElements(cmode, ccount, ckind, cindices)
}

// Enable function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnable.xml
func Enable(cap uint32) {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	C.glEnable(ccap)
}

// EnableVertexAttribArray function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnableVertexAttribArray.xml
func EnableVertexAttribArray(index uint32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	C.glEnableVertexAttribArray(cindex)
}

// Finish function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFinish.xml
func Finish() {
	C.glFinish()
}

// Flush function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFlush.xml
func Flush() {
	C.glFlush()
}

// FramebufferRenderbuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFramebufferRenderbuffer.xml
func FramebufferRenderbuffer(target uint32, attachment uint32, renderbuffertarget uint32, renderbuffer uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cattachment, _ := (C.GLenum)(attachment), cgoAllocsUnknown
	crenderbuffertarget, _ := (C.GLenum)(renderbuffertarget), cgoAllocsUnknown
	crenderbuffer, _ := (C.GLuint)(renderbuffer), cgoAllocsUnknown
	C.glFramebufferRenderbuffer(ctarget, cattachment, crenderbuffertarget, crenderbuffer)
}

// FramebufferTexture2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFramebufferTexture2D.xml
func FramebufferTexture2D(target uint32, attachment uint32, textarget uint32, texture uint32, level int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cattachment, _ := (C.GLenum)(attachment), cgoAllocsUnknown
	ctextarget, _ := (C.GLenum)(textarget), cgoAllocsUnknown
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	C.glFramebufferTexture2D(ctarget, cattachment, ctextarget, ctexture, clevel)
}

// FrontFace function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFrontFace.xml
func FrontFace(mode uint32) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glFrontFace(cmode)
}

// GenBuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenBuffers.xml
func GenBuffers(n int32, buffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glGenBuffers(cn, cbuffers)
}

// GenerateMipmap function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenerateMipmap.xml
func GenerateMipmap(target uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	C.glGenerateMipmap(ctarget)
}

// GenFramebuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenFramebuffers.xml
func GenFramebuffers(n int32, framebuffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cframebuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&framebuffers)).Data)), cgoAllocsUnknown
	C.glGenFramebuffers(cn, cframebuffers)
}

// GenRenderbuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenRenderbuffers.xml
func GenRenderbuffers(n int32, renderbuffers []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	crenderbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&renderbuffers)).Data)), cgoAllocsUnknown
	C.glGenRenderbuffers(cn, crenderbuffers)
}

// GenTextures function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenTextures.xml
func GenTextures(n int32, textures []uint32) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glGenTextures(cn, ctextures)
}

// GetActiveAttrib function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetActiveAttrib.xml
func GetActiveAttrib(program uint32, index uint32, bufSize int32, length *int32, size *int32, kind *uint32, name []byte) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	csize, _ := (*C.GLint)(unsafe.Pointer(size)), cgoAllocsUnknown
	ckind, _ := (*C.GLenum)(unsafe.Pointer(kind)), cgoAllocsUnknown
	cname, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&name)).Data)), cgoAllocsUnknown
	C.glGetActiveAttrib(cprogram, cindex, cbufSize, clength, csize, ckind, cname)
}

// GetActiveUniform function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetActiveUniform.xml
func GetActiveUniform(program uint32, index uint32, bufSize int32, length *int32, size *int32, kind *uint32, name []byte) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	csize, _ := (*C.GLint)(unsafe.Pointer(size)), cgoAllocsUnknown
	ckind, _ := (*C.GLenum)(unsafe.Pointer(kind)), cgoAllocsUnknown
	cname, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&name)).Data)), cgoAllocsUnknown
	C.glGetActiveUniform(cprogram, cindex, cbufSize, clength, csize, ckind, cname)
}

// GetAttachedShaders function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetAttachedShaders.xml
func GetAttachedShaders(program uint32, maxCount int32, count *int32, shaders []uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cmaxCount, _ := (C.GLsizei)(maxCount), cgoAllocsUnknown
	ccount, _ := (*C.GLsizei)(unsafe.Pointer(count)), cgoAllocsUnknown
	cshaders, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&shaders)).Data)), cgoAllocsUnknown
	C.glGetAttachedShaders(cprogram, cmaxCount, ccount, cshaders)
}

// GetAttribLocation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetAttribLocation.xml
func GetAttribLocation(program uint32, name string) int32 {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	__ret := C.glGetAttribLocation(cprogram, cname)
	__v := (int32)(__ret)
	return __v
}

// GetBooleanv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetBooleanv.xml
func GetBooleanv(pname uint32, data []byte) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, _ := (*C.GLboolean)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetBooleanv(cpname, cdata)
}

// GetBufferParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetBufferParameteriv.xml
func GetBufferParameteriv(target uint32, pname uint32, params *int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetBufferParameteriv(ctarget, cpname, cparams)
}

// GetError function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetError.xml
func GetError() uint32 {
	__ret := C.glGetError()
	__v := (uint32)(__ret)
	return __v
}

// GetFloatv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFloatv.xml
func GetFloatv(pname uint32, data []float32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetFloatv(cpname, cdata)
}

// GetFramebufferAttachmentParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFramebufferAttachmentParameteriv.xml
func GetFramebufferAttachmentParameteriv(target uint32, attachment uint32, pname uint32, params []int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cattachment, _ := (C.GLenum)(attachment), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetFramebufferAttachmentParameteriv(ctarget, cattachment, cpname, cparams)
}

// GetIntegerv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetIntegerv.xml
func GetIntegerv(pname uint32, data []int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetIntegerv(cpname, cdata)
}

// GetProgramiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetProgramiv.xml
func GetProgramiv(program uint32, pname uint32, params *int32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetProgramiv(cprogram, cpname, cparams)
}

// GetProgramInfoLog function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetProgramInfoLog.xml
func GetProgramInfoLog(program uint32, bufSize int32, length *int32, infoLog []byte) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	cinfoLog, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&infoLog)).Data)), cgoAllocsUnknown
	C.glGetProgramInfoLog(cprogram, cbufSize, clength, cinfoLog)
}

// GetRenderbufferParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetRenderbufferParameteriv.xml
func GetRenderbufferParameteriv(target uint32, pname uint32, params *int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetRenderbufferParameteriv(ctarget, cpname, cparams)
}

// GetShaderiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderiv.xml
func GetShaderiv(shader uint32, pname uint32, params *int32) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetShaderiv(cshader, cpname, cparams)
}

// GetShaderInfoLog function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderInfoLog.xml
func GetShaderInfoLog(shader uint32, bufSize int32, length *int32, infoLog []byte) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	cinfoLog, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&infoLog)).Data)), cgoAllocsUnknown
	C.glGetShaderInfoLog(cshader, cbufSize, clength, cinfoLog)
}

// GetShaderPrecisionFormat function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderPrecisionFormat.xml
func GetShaderPrecisionFormat(shadertype uint32, precisiontype uint32, _range []int32, precision *int32) {
	cshadertype, _ := (C.GLenum)(shadertype), cgoAllocsUnknown
	cprecisiontype, _ := (C.GLenum)(precisiontype), cgoAllocsUnknown
	c_range, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&_range)).Data)), cgoAllocsUnknown
	cprecision, _ := (*C.GLint)(unsafe.Pointer(precision)), cgoAllocsUnknown
	C.glGetShaderPrecisionFormat(cshadertype, cprecisiontype, c_range, cprecision)
}

// GetShaderSource function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderSource.xml
func GetShaderSource(shader uint32, bufSize int32, length *int32, source []byte) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	csource, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&source)).Data)), cgoAllocsUnknown
	C.glGetShaderSource(cshader, cbufSize, clength, csource)
}

// GetString function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetString.xml
func GetString(name uint32) string {
	cname, _ := (C.GLenum)(name), cgoAllocsUnknown
	__ret := C.glGetString(cname)
	__v := packPUbyteString(__ret)
	return __v
}

// GetTexParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameterfv.xml
func GetTexParameterfv(target uint32, pname uint32, params *float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetTexParameterfv(ctarget, cpname, cparams)
}

// GetTexParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameteriv.xml
func GetTexParameteriv(target uint32, pname uint32, params *int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetTexParameteriv(ctarget, cpname, cparams)
}

// GetUniformfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetUniformfv.xml
func GetUniformfv(program uint32, location int32, params *float32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetUniformfv(cprogram, clocation, cparams)
}

// GetUniformiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetUniformiv.xml
func GetUniformiv(program uint32, location int32, params *int32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetUniformiv(cprogram, clocation, cparams)
}

// GetUniformLocation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetUniformLocation.xml
func GetUniformLocation(program uint32, name string) int32 {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	__ret := C.glGetUniformLocation(cprogram, cname)
	__v := (int32)(__ret)
	return __v
}

// GetVertexAttribfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetVertexAttribfv.xml
func GetVertexAttribfv(index uint32, pname uint32, params *float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetVertexAttribfv(cindex, cpname, cparams)
}

// GetVertexAttribiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetVertexAttribiv.xml
func GetVertexAttribiv(index uint32, pname uint32, params *int32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glGetVertexAttribiv(cindex, cpname, cparams)
}

// GetVertexAttribPointerv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetVertexAttribPointerv.xml
func GetVertexAttribPointerv(index uint32, pname uint32, pointer *unsafe.Pointer) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cpointer, _ := pointer, cgoAllocsUnknown
	C.glGetVertexAttribPointerv(cindex, cpname, cpointer)
}

// Hint function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glHint.xml
func Hint(target uint32, mode uint32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glHint(ctarget, cmode)
}

// IsBuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsBuffer.xml
func IsBuffer(buffer uint32) byte {
	cbuffer, _ := (C.GLuint)(buffer), cgoAllocsUnknown
	__ret := C.glIsBuffer(cbuffer)
	__v := (byte)(__ret)
	return __v
}

// IsEnabled function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsEnabled.xml
func IsEnabled(cap uint32) byte {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	__ret := C.glIsEnabled(ccap)
	__v := (byte)(__ret)
	return __v
}

// IsFramebuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsFramebuffer.xml
func IsFramebuffer(framebuffer uint32) byte {
	cframebuffer, _ := (C.GLuint)(framebuffer), cgoAllocsUnknown
	__ret := C.glIsFramebuffer(cframebuffer)
	__v := (byte)(__ret)
	return __v
}

// IsProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsProgram.xml
func IsProgram(program uint32) byte {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	__ret := C.glIsProgram(cprogram)
	__v := (byte)(__ret)
	return __v
}

// IsRenderbuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsRenderbuffer.xml
func IsRenderbuffer(renderbuffer uint32) byte {
	crenderbuffer, _ := (C.GLuint)(renderbuffer), cgoAllocsUnknown
	__ret := C.glIsRenderbuffer(crenderbuffer)
	__v := (byte)(__ret)
	return __v
}

// IsShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsShader.xml
func IsShader(shader uint32) byte {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	__ret := C.glIsShader(cshader)
	__v := (byte)(__ret)
	return __v
}

// IsTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsTexture.xml
func IsTexture(texture uint32) byte {
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	__ret := C.glIsTexture(ctexture)
	__v := (byte)(__ret)
	return __v
}

// LineWidth function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLineWidth.xml
func LineWidth(width float32) {
	cwidth, _ := (C.GLfloat)(width), cgoAllocsUnknown
	C.glLineWidth(cwidth)
}

// LinkProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLinkProgram.xml
func LinkProgram(program uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glLinkProgram(cprogram)
}

// PixelStorei function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPixelStorei.xml
func PixelStorei(pname uint32, param int32) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glPixelStorei(cpname, cparam)
}

// PolygonOffset function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPolygonOffset.xml
func PolygonOffset(factor float32, units float32) {
	cfactor, _ := (C.GLfloat)(factor), cgoAllocsUnknown
	cunits, _ := (C.GLfloat)(units), cgoAllocsUnknown
	C.glPolygonOffset(cfactor, cunits)
}

// ReadPixels function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glReadPixels.xml
func ReadPixels(x int32, y int32, width int32, height int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := pixels, cgoAllocsUnknown
	C.glReadPixels(cx, cy, cwidth, cheight, cformat, ckind, cpixels)
}

// ReleaseShaderCompiler function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glReleaseShaderCompiler.xml
func ReleaseShaderCompiler() {
	C.glReleaseShaderCompiler()
}

// RenderbufferStorage function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glRenderbufferStorage.xml
func RenderbufferStorage(target uint32, internalformat uint32, width int32, height int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glRenderbufferStorage(ctarget, cinternalformat, cwidth, cheight)
}

// SampleCoverage function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glSampleCoverage.xml
func SampleCoverage(value float32, invert byte) {
	cvalue, _ := (C.GLfloat)(value), cgoAllocsUnknown
	cinvert, _ := (C.GLboolean)(invert), cgoAllocsUnknown
	C.glSampleCoverage(cvalue, cinvert)
}

// Scissor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glScissor.xml
func Scissor(x int32, y int32, width int32, height int32) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glScissor(cx, cy, cwidth, cheight)
}

// ShaderBinary function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glShaderBinary.xml
func ShaderBinary(count int32, shaders []uint32, binaryformat uint32, binary unsafe.Pointer, length int32) {
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cshaders, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&shaders)).Data)), cgoAllocsUnknown
	cbinaryformat, _ := (C.GLenum)(binaryformat), cgoAllocsUnknown
	cbinary, _ := binary, cgoAllocsUnknown
	clength, _ := (C.GLsizei)(length), cgoAllocsUnknown
	C.glShaderBinary(ccount, cshaders, cbinaryformat, cbinary, clength)
}

// ShaderSource function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glShaderSource.xml
func ShaderSource(shader uint32, count int32, string []string, length []int32) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cstring, _ := unpackArgSString(string)
	clength, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&length)).Data)), cgoAllocsUnknown
	C.glShaderSource(cshader, ccount, cstring, clength)
	packSString(string, cstring)
}

// StencilFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilFunc.xml
func StencilFunc(_func uint32, ref int32, mask uint32) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLint)(ref), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilFunc(c_func, cref, cmask)
}

// StencilFuncSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilFuncSeparate.xml
func StencilFuncSeparate(face uint32, _func uint32, ref int32, mask uint32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLint)(ref), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilFuncSeparate(cface, c_func, cref, cmask)
}

// StencilMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilMask.xml
func StencilMask(mask uint32) {
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilMask(cmask)
}

// StencilMaskSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilMaskSeparate.xml
func StencilMaskSeparate(face uint32, mask uint32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilMaskSeparate(cface, cmask)
}

// StencilOp function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilOp.xml
func StencilOp(fail uint32, zfail uint32, zpass uint32) {
	cfail, _ := (C.GLenum)(fail), cgoAllocsUnknown
	czfail, _ := (C.GLenum)(zfail), cgoAllocsUnknown
	czpass, _ := (C.GLenum)(zpass), cgoAllocsUnknown
	C.glStencilOp(cfail, czfail, czpass)
}

// StencilOpSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilOpSeparate.xml
func StencilOpSeparate(face uint32, sfail uint32, dpfail uint32, dppass uint32) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	csfail, _ := (C.GLenum)(sfail), cgoAllocsUnknown
	cdpfail, _ := (C.GLenum)(dpfail), cgoAllocsUnknown
	cdppass, _ := (C.GLenum)(dppass), cgoAllocsUnknown
	C.glStencilOpSeparate(cface, csfail, cdpfail, cdppass)
}

// TexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexImage2D.xml
func TexImage2D(target uint32, level int32, internalformat int32, width int32, height int32, border int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLint)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := pixels, cgoAllocsUnknown
	C.glTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cformat, ckind, cpixels)
}

// TexParameterf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterf.xml
func TexParameterf(target uint32, pname uint32, param float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glTexParameterf(ctarget, cpname, cparam)
}

// TexParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterfv.xml
func TexParameterfv(target uint32, pname uint32, params *float32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glTexParameterfv(ctarget, cpname, cparams)
}

// TexParameteri function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameteri.xml
func TexParameteri(target uint32, pname uint32, param int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glTexParameteri(ctarget, cpname, cparam)
}

// TexParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameteriv.xml
func TexParameteriv(target uint32, pname uint32, params *int32) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer(params)), cgoAllocsUnknown
	C.glTexParameteriv(ctarget, cpname, cparams)
}

// TexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexSubImage2D.xml
func TexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := pixels, cgoAllocsUnknown
	C.glTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, ckind, cpixels)
}

// Uniform1f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1f.xml
func Uniform1f(location int32, v0 float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	C.glUniform1f(clocation, cv0)
}

// Uniform1fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1fv.xml
func Uniform1fv(location int32, count int32, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform1fv(clocation, ccount, cvalue)
}

// Uniform1i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1i.xml
func Uniform1i(location int32, v0 int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	C.glUniform1i(clocation, cv0)
}

// Uniform1iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1iv.xml
func Uniform1iv(location int32, count int32, value *int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform1iv(clocation, ccount, cvalue)
}

// Uniform2f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2f.xml
func Uniform2f(location int32, v0 float32, v1 float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLfloat)(v1), cgoAllocsUnknown
	C.glUniform2f(clocation, cv0, cv1)
}

// Uniform2fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2fv.xml
func Uniform2fv(location int32, count int32, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform2fv(clocation, ccount, cvalue)
}

// Uniform2i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2i.xml
func Uniform2i(location int32, v0 int32, v1 int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLint)(v1), cgoAllocsUnknown
	C.glUniform2i(clocation, cv0, cv1)
}

// Uniform2iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2iv.xml
func Uniform2iv(location int32, count int32, value *int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform2iv(clocation, ccount, cvalue)
}

// Uniform3f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3f.xml
func Uniform3f(location int32, v0 float32, v1 float32, v2 float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLfloat)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLfloat)(v2), cgoAllocsUnknown
	C.glUniform3f(clocation, cv0, cv1, cv2)
}

// Uniform3fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3fv.xml
func Uniform3fv(location int32, count int32, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform3fv(clocation, ccount, cvalue)
}

// Uniform3i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3i.xml
func Uniform3i(location int32, v0 int32, v1 int32, v2 int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLint)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLint)(v2), cgoAllocsUnknown
	C.glUniform3i(clocation, cv0, cv1, cv2)
}

// Uniform3iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3iv.xml
func Uniform3iv(location int32, count int32, value *int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform3iv(clocation, ccount, cvalue)
}

// Uniform4f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4f.xml
func Uniform4f(location int32, v0 float32, v1 float32, v2 float32, v3 float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLfloat)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLfloat)(v2), cgoAllocsUnknown
	cv3, _ := (C.GLfloat)(v3), cgoAllocsUnknown
	C.glUniform4f(clocation, cv0, cv1, cv2, cv3)
}

// Uniform4fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4fv.xml
func Uniform4fv(location int32, count int32, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform4fv(clocation, ccount, cvalue)
}

// Uniform4i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4i.xml
func Uniform4i(location int32, v0 int32, v1 int32, v2 int32, v3 int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLint)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLint)(v2), cgoAllocsUnknown
	cv3, _ := (C.GLint)(v3), cgoAllocsUnknown
	C.glUniform4i(clocation, cv0, cv1, cv2, cv3)
}

// Uniform4iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4iv.xml
func Uniform4iv(location int32, count int32, value *int32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniform4iv(clocation, ccount, cvalue)
}

// UniformMatrix2fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniformMatrix2fv.xml
func UniformMatrix2fv(location int32, count int32, transpose byte, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ctranspose, _ := (C.GLboolean)(transpose), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniformMatrix2fv(clocation, ccount, ctranspose, cvalue)
}

// UniformMatrix3fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniformMatrix3fv.xml
func UniformMatrix3fv(location int32, count int32, transpose byte, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ctranspose, _ := (C.GLboolean)(transpose), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniformMatrix3fv(clocation, ccount, ctranspose, cvalue)
}

// UniformMatrix4fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniformMatrix4fv.xml
func UniformMatrix4fv(location int32, count int32, transpose byte, value *float32) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ctranspose, _ := (C.GLboolean)(transpose), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer(value)), cgoAllocsUnknown
	C.glUniformMatrix4fv(clocation, ccount, ctranspose, cvalue)
}

// UseProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUseProgram.xml
func UseProgram(program uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glUseProgram(cprogram)
}

// ValidateProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glValidateProgram.xml
func ValidateProgram(program uint32) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glValidateProgram(cprogram)
}

// VertexAttrib1f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib1f.xml
func VertexAttrib1f(index uint32, x float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	C.glVertexAttrib1f(cindex, cx)
}

// VertexAttrib1fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib1fv.xml
func VertexAttrib1fv(index uint32, v []float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib1fv(cindex, cv)
}

// VertexAttrib2f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib2f.xml
func VertexAttrib2f(index uint32, x float32, y float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	C.glVertexAttrib2f(cindex, cx, cy)
}

// VertexAttrib2fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib2fv.xml
func VertexAttrib2fv(index uint32, v []float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib2fv(cindex, cv)
}

// VertexAttrib3f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib3f.xml
func VertexAttrib3f(index uint32, x float32, y float32, z float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	C.glVertexAttrib3f(cindex, cx, cy, cz)
}

// VertexAttrib3fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib3fv.xml
func VertexAttrib3fv(index uint32, v []float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib3fv(cindex, cv)
}

// VertexAttrib4f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib4f.xml
func VertexAttrib4f(index uint32, x float32, y float32, z float32, w float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	cw, _ := (C.GLfloat)(w), cgoAllocsUnknown
	C.glVertexAttrib4f(cindex, cx, cy, cz, cw)
}

// VertexAttrib4fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib4fv.xml
func VertexAttrib4fv(index uint32, v []float32) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib4fv(cindex, cv)
}

// VertexAttribPointer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttribPointer.xml
func VertexAttribPointer(index uint32, size int32, kind uint32, normalized byte, stride int32, pointer unsafe.Pointer) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	csize, _ := (C.GLint)(size), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cnormalized, _ := (C.GLboolean)(normalized), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := pointer, cgoAllocsUnknown
	C.glVertexAttribPointer(cindex, csize, ckind, cnormalized, cstride, cpointer)
}

// Viewport function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glViewport.xml
func Viewport(x int32, y int32, width int32, height int32) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glViewport(cx, cy, cwidth, cheight)
}
