// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 22 Sep 2016 02:15:07 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package gles2

/*
#cgo LDFLAGS: -lGLESv2
#include <GLES2/gl2.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// SetActiveTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glActiveTexture.xml
func SetActiveTexture(texture Enum) {
	ctexture, _ := (C.GLenum)(texture), cgoAllocsUnknown
	C.glActiveTexture(ctexture)
}

// AttachShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glAttachShader.xml
func AttachShader(program Uint, shader Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glAttachShader(cprogram, cshader)
}

// BindAttribLocation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindAttribLocation.xml
func BindAttribLocation(program Uint, index Uint, name string) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	C.glBindAttribLocation(cprogram, cindex, cname)
}

// BindBuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindBuffer.xml
func BindBuffer(target Enum, buffer Uint) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cbuffer, _ := (C.GLuint)(buffer), cgoAllocsUnknown
	C.glBindBuffer(ctarget, cbuffer)
}

// BindFramebuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindFramebuffer.xml
func BindFramebuffer(target Enum, framebuffer Uint) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cframebuffer, _ := (C.GLuint)(framebuffer), cgoAllocsUnknown
	C.glBindFramebuffer(ctarget, cframebuffer)
}

// BindRenderbuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindRenderbuffer.xml
func BindRenderbuffer(target Enum, renderbuffer Uint) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	crenderbuffer, _ := (C.GLuint)(renderbuffer), cgoAllocsUnknown
	C.glBindRenderbuffer(ctarget, crenderbuffer)
}

// BindTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBindTexture.xml
func BindTexture(target Enum, texture Uint) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	C.glBindTexture(ctarget, ctexture)
}

// SetBlendColor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendColor.xml
func SetBlendColor(red Float, green Float, blue Float, alpha Float) {
	cred, _ := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, _ := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glBlendColor(cred, cgreen, cblue, calpha)
}

// SetBlendEquation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendEquation.xml
func SetBlendEquation(mode Enum) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glBlendEquation(cmode)
}

// BlendEquationSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendEquationSeparate.xml
func BlendEquationSeparate(modeRGB Enum, modeAlpha Enum) {
	cmodeRGB, _ := (C.GLenum)(modeRGB), cgoAllocsUnknown
	cmodeAlpha, _ := (C.GLenum)(modeAlpha), cgoAllocsUnknown
	C.glBlendEquationSeparate(cmodeRGB, cmodeAlpha)
}

// BlendFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendFunc.xml
func BlendFunc(sfactor Enum, dfactor Enum) {
	csfactor, _ := (C.GLenum)(sfactor), cgoAllocsUnknown
	cdfactor, _ := (C.GLenum)(dfactor), cgoAllocsUnknown
	C.glBlendFunc(csfactor, cdfactor)
}

// BlendFuncSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBlendFuncSeparate.xml
func BlendFuncSeparate(sfactorRGB Enum, dfactorRGB Enum, sfactorAlpha Enum, dfactorAlpha Enum) {
	csfactorRGB, _ := (C.GLenum)(sfactorRGB), cgoAllocsUnknown
	cdfactorRGB, _ := (C.GLenum)(dfactorRGB), cgoAllocsUnknown
	csfactorAlpha, _ := (C.GLenum)(sfactorAlpha), cgoAllocsUnknown
	cdfactorAlpha, _ := (C.GLenum)(dfactorAlpha), cgoAllocsUnknown
	C.glBlendFuncSeparate(csfactorRGB, cdfactorRGB, csfactorAlpha, cdfactorAlpha)
}

// BufferData function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBufferData.xml
func BufferData(target Enum, size Sizeiptr, data unsafe.Pointer, usage Enum) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	csize, _ := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	cusage, _ := (C.GLenum)(usage), cgoAllocsUnknown
	C.glBufferData(ctarget, csize, cdata, cusage)
}

// BufferSubData function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glBufferSubData.xml
func BufferSubData(target Enum, offset Intptr, size Sizeiptr, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	coffset, _ := (C.GLintptr)(offset), cgoAllocsUnknown
	csize, _ := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	C.glBufferSubData(ctarget, coffset, csize, cdata)
}

// CheckFramebufferStatus function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCheckFramebufferStatus.xml
func CheckFramebufferStatus(target Enum) Enum {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	__ret := C.glCheckFramebufferStatus(ctarget)
	__v := (Enum)(__ret)
	return __v
}

// Clear function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClear.xml
func Clear(mask Bitfield) {
	cmask, _ := (C.GLbitfield)(mask), cgoAllocsUnknown
	C.glClear(cmask)
}

// ClearColor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearColor.xml
func ClearColor(red Float, green Float, blue Float, alpha Float) {
	cred, _ := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, _ := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glClearColor(cred, cgreen, cblue, calpha)
}

// ClearDepthf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearDepthf.xml
func ClearDepthf(d Float) {
	cd, _ := (C.GLfloat)(d), cgoAllocsUnknown
	C.glClearDepthf(cd)
}

// ClearStencil function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glClearStencil.xml
func ClearStencil(s Int) {
	cs, _ := (C.GLint)(s), cgoAllocsUnknown
	C.glClearStencil(cs)
}

// ColorMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glColorMask.xml
func ColorMask(red Boolean, green Boolean, blue Boolean, alpha Boolean) {
	cred, _ := (C.GLboolean)(red), cgoAllocsUnknown
	cgreen, _ := (C.GLboolean)(green), cgoAllocsUnknown
	cblue, _ := (C.GLboolean)(blue), cgoAllocsUnknown
	calpha, _ := (C.GLboolean)(alpha), cgoAllocsUnknown
	C.glColorMask(cred, cgreen, cblue, calpha)
}

// CompileShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompileShader.xml
func CompileShader(shader Uint) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glCompileShader(cshader)
}

// CompressedTexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompressedTexImage2D.xml
func CompressedTexImage2D(target Enum, level Int, internalformat Enum, width Sizei, height Sizei, border Int, imageSize Sizei, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	cimageSize, _ := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	C.glCompressedTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cimageSize, cdata)
}

// CompressedTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCompressedTexSubImage2D.xml
func CompressedTexSubImage2D(target Enum, level Int, xoffset Int, yoffset Int, width Sizei, height Sizei, format Enum, imageSize Sizei, data unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	cimageSize, _ := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, _ := (unsafe.Pointer)(unsafe.Pointer(data)), cgoAllocsUnknown
	C.glCompressedTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, cimageSize, cdata)
}

// CopyTexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCopyTexImage2D.xml
func CopyTexImage2D(target Enum, level Int, internalformat Enum, x Int, y Int, width Sizei, height Sizei, border Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	C.glCopyTexImage2D(ctarget, clevel, cinternalformat, cx, cy, cwidth, cheight, cborder)
}

// CopyTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCopyTexSubImage2D.xml
func CopyTexSubImage2D(target Enum, level Int, xoffset Int, yoffset Int, x Int, y Int, width Sizei, height Sizei) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glCopyTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cx, cy, cwidth, cheight)
}

// CreateProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCreateProgram.xml
func CreateProgram() Uint {
	__ret := C.glCreateProgram()
	__v := (Uint)(__ret)
	return __v
}

// CreateShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCreateShader.xml
func CreateShader(kind Enum) Uint {
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	__ret := C.glCreateShader(ckind)
	__v := (Uint)(__ret)
	return __v
}

// SetCullFace function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCullFace.xml
func SetCullFace(mode Enum) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glCullFace(cmode)
}

// DeleteBuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteBuffers.xml
func DeleteBuffers(n Sizei, buffers []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glDeleteBuffers(cn, cbuffers)
}

// DeleteFramebuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteFramebuffers.xml
func DeleteFramebuffers(n Sizei, framebuffers []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cframebuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&framebuffers)).Data)), cgoAllocsUnknown
	C.glDeleteFramebuffers(cn, cframebuffers)
}

// DeleteProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteProgram.xml
func DeleteProgram(program Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glDeleteProgram(cprogram)
}

// DeleteRenderbuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteRenderbuffers.xml
func DeleteRenderbuffers(n Sizei, renderbuffers []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	crenderbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&renderbuffers)).Data)), cgoAllocsUnknown
	C.glDeleteRenderbuffers(cn, crenderbuffers)
}

// DeleteShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteShader.xml
func DeleteShader(shader Uint) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glDeleteShader(cshader)
}

// DeleteTextures function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteTextures.xml
func DeleteTextures(n Sizei, textures []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glDeleteTextures(cn, ctextures)
}

// SetDepthFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthFunc.xml
func SetDepthFunc(_func Enum) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	C.glDepthFunc(c_func)
}

// DepthMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthMask.xml
func DepthMask(flag Boolean) {
	cflag, _ := (C.GLboolean)(flag), cgoAllocsUnknown
	C.glDepthMask(cflag)
}

// DepthRangef function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDepthRangef.xml
func DepthRangef(n Float, f Float) {
	cn, _ := (C.GLfloat)(n), cgoAllocsUnknown
	cf, _ := (C.GLfloat)(f), cgoAllocsUnknown
	C.glDepthRangef(cn, cf)
}

// DetachShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDetachShader.xml
func DetachShader(program Uint, shader Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	C.glDetachShader(cprogram, cshader)
}

// Disable function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDisable.xml
func Disable(cap Enum) {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	C.glDisable(ccap)
}

// DisableVertexAttribArray function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDisableVertexAttribArray.xml
func DisableVertexAttribArray(index Uint) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	C.glDisableVertexAttribArray(cindex)
}

// DrawArrays function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDrawArrays.xml
func DrawArrays(mode Enum, first Int, count Sizei) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	cfirst, _ := (C.GLint)(first), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	C.glDrawArrays(cmode, cfirst, ccount)
}

// DrawElements function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDrawElements.xml
func DrawElements(mode Enum, count Sizei, kind Enum, indices unsafe.Pointer) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cindices, _ := (unsafe.Pointer)(unsafe.Pointer(indices)), cgoAllocsUnknown
	C.glDrawElements(cmode, ccount, ckind, cindices)
}

// Enable function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnable.xml
func Enable(cap Enum) {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	C.glEnable(ccap)
}

// EnableVertexAttribArray function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnableVertexAttribArray.xml
func EnableVertexAttribArray(index Uint) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	C.glEnableVertexAttribArray(cindex)
}

// Finish function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFinish.xml
func Finish() {
	C.glFinish()
}

// Flush function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFlush.xml
func Flush() {
	C.glFlush()
}

// FramebufferRenderbuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFramebufferRenderbuffer.xml
func FramebufferRenderbuffer(target Enum, attachment Enum, renderbuffertarget Enum, renderbuffer Uint) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cattachment, _ := (C.GLenum)(attachment), cgoAllocsUnknown
	crenderbuffertarget, _ := (C.GLenum)(renderbuffertarget), cgoAllocsUnknown
	crenderbuffer, _ := (C.GLuint)(renderbuffer), cgoAllocsUnknown
	C.glFramebufferRenderbuffer(ctarget, cattachment, crenderbuffertarget, crenderbuffer)
}

// FramebufferTexture2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFramebufferTexture2D.xml
func FramebufferTexture2D(target Enum, attachment Enum, textarget Enum, texture Uint, level Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cattachment, _ := (C.GLenum)(attachment), cgoAllocsUnknown
	ctextarget, _ := (C.GLenum)(textarget), cgoAllocsUnknown
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	C.glFramebufferTexture2D(ctarget, cattachment, ctextarget, ctexture, clevel)
}

// SetFrontFace function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glFrontFace.xml
func SetFrontFace(mode Enum) {
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glFrontFace(cmode)
}

// GenBuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenBuffers.xml
func GenBuffers(n Sizei, buffers []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glGenBuffers(cn, cbuffers)
}

// GenerateMipmap function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenerateMipmap.xml
func GenerateMipmap(target Enum) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	C.glGenerateMipmap(ctarget)
}

// GenFramebuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenFramebuffers.xml
func GenFramebuffers(n Sizei, framebuffers []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	cframebuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&framebuffers)).Data)), cgoAllocsUnknown
	C.glGenFramebuffers(cn, cframebuffers)
}

// GenRenderbuffers function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenRenderbuffers.xml
func GenRenderbuffers(n Sizei, renderbuffers []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	crenderbuffers, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&renderbuffers)).Data)), cgoAllocsUnknown
	C.glGenRenderbuffers(cn, crenderbuffers)
}

// GenTextures function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenTextures.xml
func GenTextures(n Sizei, textures []Uint) {
	cn, _ := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glGenTextures(cn, ctextures)
}

// GetActiveAttrib function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetActiveAttrib.xml
func GetActiveAttrib(program Uint, index Uint, bufSize Sizei, length *Sizei, size *Int, kind *Enum, name []byte) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	csize, _ := (*C.GLint)(unsafe.Pointer(size)), cgoAllocsUnknown
	ckind, _ := (*C.GLenum)(unsafe.Pointer(kind)), cgoAllocsUnknown
	cname, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&name)).Data)), cgoAllocsUnknown
	C.glGetActiveAttrib(cprogram, cindex, cbufSize, clength, csize, ckind, cname)
}

// GetActiveUniform function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetActiveUniform.xml
func GetActiveUniform(program Uint, index Uint, bufSize Sizei, length *Sizei, size *Int, kind *Enum, name []byte) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	csize, _ := (*C.GLint)(unsafe.Pointer(size)), cgoAllocsUnknown
	ckind, _ := (*C.GLenum)(unsafe.Pointer(kind)), cgoAllocsUnknown
	cname, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&name)).Data)), cgoAllocsUnknown
	C.glGetActiveUniform(cprogram, cindex, cbufSize, clength, csize, ckind, cname)
}

// GetAttachedShaders function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetAttachedShaders.xml
func GetAttachedShaders(program Uint, maxCount Sizei, count *Sizei, shaders []Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cmaxCount, _ := (C.GLsizei)(maxCount), cgoAllocsUnknown
	ccount, _ := (*C.GLsizei)(unsafe.Pointer(count)), cgoAllocsUnknown
	cshaders, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&shaders)).Data)), cgoAllocsUnknown
	C.glGetAttachedShaders(cprogram, cmaxCount, ccount, cshaders)
}

// GetAttribLocation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetAttribLocation.xml
func GetAttribLocation(program Uint, name string) Int {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	__ret := C.glGetAttribLocation(cprogram, cname)
	__v := (Int)(__ret)
	return __v
}

// GetBooleanv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetBooleanv.xml
func GetBooleanv(pname Enum, data []Boolean) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, _ := (*C.GLboolean)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetBooleanv(cpname, cdata)
}

// GetBufferParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetBufferParameteriv.xml
func GetBufferParameteriv(target Enum, pname Enum, params []Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetBufferParameteriv(ctarget, cpname, cparams)
}

// GetError function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetError.xml
func GetError() Enum {
	__ret := C.glGetError()
	__v := (Enum)(__ret)
	return __v
}

// GetFloatv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFloatv.xml
func GetFloatv(pname Enum, data []Float) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetFloatv(cpname, cdata)
}

// GetFramebufferAttachmentParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFramebufferAttachmentParameteriv.xml
func GetFramebufferAttachmentParameteriv(target Enum, attachment Enum, pname Enum, params []Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cattachment, _ := (C.GLenum)(attachment), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetFramebufferAttachmentParameteriv(ctarget, cattachment, cpname, cparams)
}

// GetIntegerv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetIntegerv.xml
func GetIntegerv(pname Enum, data []Int) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetIntegerv(cpname, cdata)
}

// GetProgramiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetProgramiv.xml
func GetProgramiv(program Uint, pname Enum, params []Int) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetProgramiv(cprogram, cpname, cparams)
}

// GetProgramInfoLog function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetProgramInfoLog.xml
func GetProgramInfoLog(program Uint, bufSize Sizei, length *Sizei, infoLog []byte) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	cinfoLog, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&infoLog)).Data)), cgoAllocsUnknown
	C.glGetProgramInfoLog(cprogram, cbufSize, clength, cinfoLog)
}

// GetRenderbufferParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetRenderbufferParameteriv.xml
func GetRenderbufferParameteriv(target Enum, pname Enum, params []Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetRenderbufferParameteriv(ctarget, cpname, cparams)
}

// GetShaderiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderiv.xml
func GetShaderiv(shader Uint, pname Enum, params []Int) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetShaderiv(cshader, cpname, cparams)
}

// GetShaderInfoLog function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderInfoLog.xml
func GetShaderInfoLog(shader Uint, bufSize Sizei, length *Sizei, infoLog []byte) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	cinfoLog, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&infoLog)).Data)), cgoAllocsUnknown
	C.glGetShaderInfoLog(cshader, cbufSize, clength, cinfoLog)
}

// GetShaderPrecisionFormat function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderPrecisionFormat.xml
func GetShaderPrecisionFormat(shadertype Enum, precisiontype Enum, _range []Int, precision *Int) {
	cshadertype, _ := (C.GLenum)(shadertype), cgoAllocsUnknown
	cprecisiontype, _ := (C.GLenum)(precisiontype), cgoAllocsUnknown
	c_range, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&_range)).Data)), cgoAllocsUnknown
	cprecision, _ := (*C.GLint)(unsafe.Pointer(precision)), cgoAllocsUnknown
	C.glGetShaderPrecisionFormat(cshadertype, cprecisiontype, c_range, cprecision)
}

// GetShaderSource function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetShaderSource.xml
func GetShaderSource(shader Uint, bufSize Sizei, length *Sizei, source []byte) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	cbufSize, _ := (C.GLsizei)(bufSize), cgoAllocsUnknown
	clength, _ := (*C.GLsizei)(unsafe.Pointer(length)), cgoAllocsUnknown
	csource, _ := (*C.GLchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&source)).Data)), cgoAllocsUnknown
	C.glGetShaderSource(cshader, cbufSize, clength, csource)
}

// GetString function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetString.xml
func GetString(name Enum) string {
	cname, _ := (C.GLenum)(name), cgoAllocsUnknown
	__ret := C.glGetString(cname)
	__v := packPUbyteString(__ret)
	return __v
}

// GetTexParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameterfv.xml
func GetTexParameterfv(target Enum, pname Enum, params []Float) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameterfv(ctarget, cpname, cparams)
}

// GetTexParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetTexParameteriv.xml
func GetTexParameteriv(target Enum, pname Enum, params []Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameteriv(ctarget, cpname, cparams)
}

// GetUniformfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetUniformfv.xml
func GetUniformfv(program Uint, location Int, params []Float) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetUniformfv(cprogram, clocation, cparams)
}

// GetUniformiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetUniformiv.xml
func GetUniformiv(program Uint, location Int, params []Int) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetUniformiv(cprogram, clocation, cparams)
}

// GetUniformLocation function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetUniformLocation.xml
func GetUniformLocation(program Uint, name string) Int {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	__ret := C.glGetUniformLocation(cprogram, cname)
	__v := (Int)(__ret)
	return __v
}

// GetVertexAttribfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetVertexAttribfv.xml
func GetVertexAttribfv(index Uint, pname Enum, params []Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetVertexAttribfv(cindex, cpname, cparams)
}

// GetVertexAttribiv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetVertexAttribiv.xml
func GetVertexAttribiv(index Uint, pname Enum, params []Int) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetVertexAttribiv(cindex, cpname, cparams)
}

// GetVertexAttribPointerv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetVertexAttribPointerv.xml
func GetVertexAttribPointerv(index Uint, pname Enum, pointer *unsafe.Pointer) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cpointer, _ := (*unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glGetVertexAttribPointerv(cindex, cpname, cpointer)
}

// Hint function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glHint.xml
func Hint(target Enum, mode Enum) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cmode, _ := (C.GLenum)(mode), cgoAllocsUnknown
	C.glHint(ctarget, cmode)
}

// IsBuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsBuffer.xml
func IsBuffer(buffer Uint) Boolean {
	cbuffer, _ := (C.GLuint)(buffer), cgoAllocsUnknown
	__ret := C.glIsBuffer(cbuffer)
	__v := (Boolean)(__ret)
	return __v
}

// IsEnabled function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsEnabled.xml
func IsEnabled(cap Enum) Boolean {
	ccap, _ := (C.GLenum)(cap), cgoAllocsUnknown
	__ret := C.glIsEnabled(ccap)
	__v := (Boolean)(__ret)
	return __v
}

// IsFramebuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsFramebuffer.xml
func IsFramebuffer(framebuffer Uint) Boolean {
	cframebuffer, _ := (C.GLuint)(framebuffer), cgoAllocsUnknown
	__ret := C.glIsFramebuffer(cframebuffer)
	__v := (Boolean)(__ret)
	return __v
}

// IsProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsProgram.xml
func IsProgram(program Uint) Boolean {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	__ret := C.glIsProgram(cprogram)
	__v := (Boolean)(__ret)
	return __v
}

// IsRenderbuffer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsRenderbuffer.xml
func IsRenderbuffer(renderbuffer Uint) Boolean {
	crenderbuffer, _ := (C.GLuint)(renderbuffer), cgoAllocsUnknown
	__ret := C.glIsRenderbuffer(crenderbuffer)
	__v := (Boolean)(__ret)
	return __v
}

// IsShader function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsShader.xml
func IsShader(shader Uint) Boolean {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	__ret := C.glIsShader(cshader)
	__v := (Boolean)(__ret)
	return __v
}

// IsTexture function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glIsTexture.xml
func IsTexture(texture Uint) Boolean {
	ctexture, _ := (C.GLuint)(texture), cgoAllocsUnknown
	__ret := C.glIsTexture(ctexture)
	__v := (Boolean)(__ret)
	return __v
}

// SetLineWidth function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLineWidth.xml
func SetLineWidth(width Float) {
	cwidth, _ := (C.GLfloat)(width), cgoAllocsUnknown
	C.glLineWidth(cwidth)
}

// LinkProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glLinkProgram.xml
func LinkProgram(program Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glLinkProgram(cprogram)
}

// PixelStorei function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPixelStorei.xml
func PixelStorei(pname Enum, param Int) {
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glPixelStorei(cpname, cparam)
}

// PolygonOffset function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPolygonOffset.xml
func PolygonOffset(factor Float, units Float) {
	cfactor, _ := (C.GLfloat)(factor), cgoAllocsUnknown
	cunits, _ := (C.GLfloat)(units), cgoAllocsUnknown
	C.glPolygonOffset(cfactor, cunits)
}

// ReadPixels function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glReadPixels.xml
func ReadPixels(x Int, y Int, width Sizei, height Sizei, format Enum, kind Enum, pixels unsafe.Pointer) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := (unsafe.Pointer)(unsafe.Pointer(pixels)), cgoAllocsUnknown
	C.glReadPixels(cx, cy, cwidth, cheight, cformat, ckind, cpixels)
}

// ReleaseShaderCompiler function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glReleaseShaderCompiler.xml
func ReleaseShaderCompiler() {
	C.glReleaseShaderCompiler()
}

// RenderbufferStorage function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glRenderbufferStorage.xml
func RenderbufferStorage(target Enum, internalformat Enum, width Sizei, height Sizei) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cinternalformat, _ := (C.GLenum)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glRenderbufferStorage(ctarget, cinternalformat, cwidth, cheight)
}

// SetSampleCoverage function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glSampleCoverage.xml
func SetSampleCoverage(value Float, invert Boolean) {
	cvalue, _ := (C.GLfloat)(value), cgoAllocsUnknown
	cinvert, _ := (C.GLboolean)(invert), cgoAllocsUnknown
	C.glSampleCoverage(cvalue, cinvert)
}

// Scissor function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glScissor.xml
func Scissor(x Int, y Int, width Sizei, height Sizei) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glScissor(cx, cy, cwidth, cheight)
}

// ShaderBinary function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glShaderBinary.xml
func ShaderBinary(count Sizei, shaders []Uint, binaryformat Enum, binary unsafe.Pointer, length Sizei) {
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cshaders, _ := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&shaders)).Data)), cgoAllocsUnknown
	cbinaryformat, _ := (C.GLenum)(binaryformat), cgoAllocsUnknown
	cbinary, _ := (unsafe.Pointer)(unsafe.Pointer(binary)), cgoAllocsUnknown
	clength, _ := (C.GLsizei)(length), cgoAllocsUnknown
	C.glShaderBinary(ccount, cshaders, cbinaryformat, cbinary, clength)
}

// ShaderSource function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glShaderSource.xml
func ShaderSource(shader Uint, count Sizei, string []string, length []Int) {
	cshader, _ := (C.GLuint)(shader), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cstring, _ := unpackArgSString(string)
	clength, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&length)).Data)), cgoAllocsUnknown
	C.glShaderSource(cshader, ccount, cstring, clength)
	packSString(string, cstring)
}

// SetStencilFunc function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilFunc.xml
func SetStencilFunc(_func Enum, ref Int, mask Uint) {
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLint)(ref), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilFunc(c_func, cref, cmask)
}

// StencilFuncSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilFuncSeparate.xml
func StencilFuncSeparate(face Enum, _func Enum, ref Int, mask Uint) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	c_func, _ := (C.GLenum)(_func), cgoAllocsUnknown
	cref, _ := (C.GLint)(ref), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilFuncSeparate(cface, c_func, cref, cmask)
}

// StencilMask function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilMask.xml
func StencilMask(mask Uint) {
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilMask(cmask)
}

// StencilMaskSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilMaskSeparate.xml
func StencilMaskSeparate(face Enum, mask Uint) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	cmask, _ := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilMaskSeparate(cface, cmask)
}

// StencilOp function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilOp.xml
func StencilOp(fail Enum, zfail Enum, zpass Enum) {
	cfail, _ := (C.GLenum)(fail), cgoAllocsUnknown
	czfail, _ := (C.GLenum)(zfail), cgoAllocsUnknown
	czpass, _ := (C.GLenum)(zpass), cgoAllocsUnknown
	C.glStencilOp(cfail, czfail, czpass)
}

// StencilOpSeparate function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glStencilOpSeparate.xml
func StencilOpSeparate(face Enum, sfail Enum, dpfail Enum, dppass Enum) {
	cface, _ := (C.GLenum)(face), cgoAllocsUnknown
	csfail, _ := (C.GLenum)(sfail), cgoAllocsUnknown
	cdpfail, _ := (C.GLenum)(dpfail), cgoAllocsUnknown
	cdppass, _ := (C.GLenum)(dppass), cgoAllocsUnknown
	C.glStencilOpSeparate(cface, csfail, cdpfail, cdppass)
}

// TexImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexImage2D.xml
func TexImage2D(target Enum, level Int, internalformat Int, width Sizei, height Sizei, border Int, format Enum, kind Enum, pixels unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, _ := (C.GLint)(internalformat), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, _ := (C.GLint)(border), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := (unsafe.Pointer)(unsafe.Pointer(pixels)), cgoAllocsUnknown
	C.glTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cformat, ckind, cpixels)
}

// TexParameterf function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterf.xml
func TexParameterf(target Enum, pname Enum, param Float) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLfloat)(param), cgoAllocsUnknown
	C.glTexParameterf(ctarget, cpname, cparam)
}

// TexParameterfv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameterfv.xml
func TexParameterfv(target Enum, pname Enum, params []Float) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameterfv(ctarget, cpname, cparams)
}

// TexParameteri function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameteri.xml
func TexParameteri(target Enum, pname Enum, param Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, _ := (C.GLint)(param), cgoAllocsUnknown
	C.glTexParameteri(ctarget, cpname, cparam)
}

// TexParameteriv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameteriv.xml
func TexParameteriv(target Enum, pname Enum, params []Int) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	cpname, _ := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameteriv(ctarget, cpname, cparams)
}

// TexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexSubImage2D.xml
func TexSubImage2D(target Enum, level Int, xoffset Int, yoffset Int, width Sizei, height Sizei, format Enum, kind Enum, pixels unsafe.Pointer) {
	ctarget, _ := (C.GLenum)(target), cgoAllocsUnknown
	clevel, _ := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, _ := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, _ := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, _ := (C.GLenum)(format), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, _ := (unsafe.Pointer)(unsafe.Pointer(pixels)), cgoAllocsUnknown
	C.glTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, ckind, cpixels)
}

// Uniform1f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1f.xml
func Uniform1f(location Int, v0 Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	C.glUniform1f(clocation, cv0)
}

// Uniform1fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1fv.xml
func Uniform1fv(location Int, count Sizei, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform1fv(clocation, ccount, cvalue)
}

// Uniform1i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1i.xml
func Uniform1i(location Int, v0 Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	C.glUniform1i(clocation, cv0)
}

// Uniform1iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform1iv.xml
func Uniform1iv(location Int, count Sizei, value []Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform1iv(clocation, ccount, cvalue)
}

// Uniform2f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2f.xml
func Uniform2f(location Int, v0 Float, v1 Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLfloat)(v1), cgoAllocsUnknown
	C.glUniform2f(clocation, cv0, cv1)
}

// Uniform2fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2fv.xml
func Uniform2fv(location Int, count Sizei, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform2fv(clocation, ccount, cvalue)
}

// Uniform2i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2i.xml
func Uniform2i(location Int, v0 Int, v1 Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLint)(v1), cgoAllocsUnknown
	C.glUniform2i(clocation, cv0, cv1)
}

// Uniform2iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform2iv.xml
func Uniform2iv(location Int, count Sizei, value []Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform2iv(clocation, ccount, cvalue)
}

// Uniform3f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3f.xml
func Uniform3f(location Int, v0 Float, v1 Float, v2 Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLfloat)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLfloat)(v2), cgoAllocsUnknown
	C.glUniform3f(clocation, cv0, cv1, cv2)
}

// Uniform3fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3fv.xml
func Uniform3fv(location Int, count Sizei, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform3fv(clocation, ccount, cvalue)
}

// Uniform3i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3i.xml
func Uniform3i(location Int, v0 Int, v1 Int, v2 Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLint)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLint)(v2), cgoAllocsUnknown
	C.glUniform3i(clocation, cv0, cv1, cv2)
}

// Uniform3iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform3iv.xml
func Uniform3iv(location Int, count Sizei, value []Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform3iv(clocation, ccount, cvalue)
}

// Uniform4f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4f.xml
func Uniform4f(location Int, v0 Float, v1 Float, v2 Float, v3 Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLfloat)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLfloat)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLfloat)(v2), cgoAllocsUnknown
	cv3, _ := (C.GLfloat)(v3), cgoAllocsUnknown
	C.glUniform4f(clocation, cv0, cv1, cv2, cv3)
}

// Uniform4fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4fv.xml
func Uniform4fv(location Int, count Sizei, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform4fv(clocation, ccount, cvalue)
}

// Uniform4i function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4i.xml
func Uniform4i(location Int, v0 Int, v1 Int, v2 Int, v3 Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	cv0, _ := (C.GLint)(v0), cgoAllocsUnknown
	cv1, _ := (C.GLint)(v1), cgoAllocsUnknown
	cv2, _ := (C.GLint)(v2), cgoAllocsUnknown
	cv3, _ := (C.GLint)(v3), cgoAllocsUnknown
	C.glUniform4i(clocation, cv0, cv1, cv2, cv3)
}

// Uniform4iv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniform4iv.xml
func Uniform4iv(location Int, count Sizei, value []Int) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	cvalue, _ := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniform4iv(clocation, ccount, cvalue)
}

// UniformMatrix2fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniformMatrix2fv.xml
func UniformMatrix2fv(location Int, count Sizei, transpose Boolean, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ctranspose, _ := (C.GLboolean)(transpose), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniformMatrix2fv(clocation, ccount, ctranspose, cvalue)
}

// UniformMatrix3fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniformMatrix3fv.xml
func UniformMatrix3fv(location Int, count Sizei, transpose Boolean, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ctranspose, _ := (C.GLboolean)(transpose), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniformMatrix3fv(clocation, ccount, ctranspose, cvalue)
}

// UniformMatrix4fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUniformMatrix4fv.xml
func UniformMatrix4fv(location Int, count Sizei, transpose Boolean, value []Float) {
	clocation, _ := (C.GLint)(location), cgoAllocsUnknown
	ccount, _ := (C.GLsizei)(count), cgoAllocsUnknown
	ctranspose, _ := (C.GLboolean)(transpose), cgoAllocsUnknown
	cvalue, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&value)).Data)), cgoAllocsUnknown
	C.glUniformMatrix4fv(clocation, ccount, ctranspose, cvalue)
}

// UseProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glUseProgram.xml
func UseProgram(program Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glUseProgram(cprogram)
}

// ValidateProgram function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glValidateProgram.xml
func ValidateProgram(program Uint) {
	cprogram, _ := (C.GLuint)(program), cgoAllocsUnknown
	C.glValidateProgram(cprogram)
}

// VertexAttrib1f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib1f.xml
func VertexAttrib1f(index Uint, x Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	C.glVertexAttrib1f(cindex, cx)
}

// VertexAttrib1fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib1fv.xml
func VertexAttrib1fv(index Uint, v []Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib1fv(cindex, cv)
}

// VertexAttrib2f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib2f.xml
func VertexAttrib2f(index Uint, x Float, y Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	C.glVertexAttrib2f(cindex, cx, cy)
}

// VertexAttrib2fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib2fv.xml
func VertexAttrib2fv(index Uint, v []Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib2fv(cindex, cv)
}

// VertexAttrib3f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib3f.xml
func VertexAttrib3f(index Uint, x Float, y Float, z Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	C.glVertexAttrib3f(cindex, cx, cy, cz)
}

// VertexAttrib3fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib3fv.xml
func VertexAttrib3fv(index Uint, v []Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib3fv(cindex, cv)
}

// VertexAttrib4f function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib4f.xml
func VertexAttrib4f(index Uint, x Float, y Float, z Float, w Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cx, _ := (C.GLfloat)(x), cgoAllocsUnknown
	cy, _ := (C.GLfloat)(y), cgoAllocsUnknown
	cz, _ := (C.GLfloat)(z), cgoAllocsUnknown
	cw, _ := (C.GLfloat)(w), cgoAllocsUnknown
	C.glVertexAttrib4f(cindex, cx, cy, cz, cw)
}

// VertexAttrib4fv function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttrib4fv.xml
func VertexAttrib4fv(index Uint, v []Float) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	cv, _ := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&v)).Data)), cgoAllocsUnknown
	C.glVertexAttrib4fv(cindex, cv)
}

// VertexAttribPointer function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttribPointer.xml
func VertexAttribPointer(index Uint, size Int, kind Enum, normalized Boolean, stride Sizei, pointer unsafe.Pointer) {
	cindex, _ := (C.GLuint)(index), cgoAllocsUnknown
	csize, _ := (C.GLint)(size), cgoAllocsUnknown
	ckind, _ := (C.GLenum)(kind), cgoAllocsUnknown
	cnormalized, _ := (C.GLboolean)(normalized), cgoAllocsUnknown
	cstride, _ := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, _ := (unsafe.Pointer)(unsafe.Pointer(pointer)), cgoAllocsUnknown
	C.glVertexAttribPointer(cindex, csize, ckind, cnormalized, cstride, cpointer)
}

// SetViewport function as declared in https://www.khronos.org/opengles/sdk/docs/man/xhtml/glViewport.xml
func SetViewport(x Int, y Int, width Sizei, height Sizei) {
	cx, _ := (C.GLint)(x), cgoAllocsUnknown
	cy, _ := (C.GLint)(y), cgoAllocsUnknown
	cwidth, _ := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, _ := (C.GLsizei)(height), cgoAllocsUnknown
	C.glViewport(cx, cy, cwidth, cheight)
}
